### ISSUE TITLE
How to get Columns name and write to particular Column  ?

### ISSUE THREAD

**Issue by codetrash** [box/spout#116]
Halooo

How to get Columns name and write to particular Column  ?

**Comment by adrilo** [comment]
Hi @codetrash,

Can you please specify what you mean by "Columns name"? Are you talking about A, B, C... or some kind of headers?

Regarding writing to a particular column, this is not supported. In order to keep memory usage low, Spout only keeps in memory the row it will write and immediately forgets about already written rows. This also makes it "impossible" to write data to a random cell.
However, you can work around this limitation by creating row data in a specific way. For instance, if you need to write this data: `A1 => 'foo'`, `C1 => 'bar'`, `B3 => 'baz'`, you can do something like this:

```php
$writer->addRows([
    ['foo', '', 'bar'],
    [''], // the empty string is required to add a blank row
    ['', 'baz'],
]);
```

**Comment by codetrash** [comment]
Oooh I get....that makes sense...keeping the memory as low as possible...thx
