### ISSUE TITLE
ZipHelper close hits max execution time

### ISSUE THREAD

**Issue by axelvnk** [box/spout#119]
First of all, great library! So thanks! :) 

I'm reading a CSV with about 25k lines and at the same time writing it into an Excel file. 

``````
        /** @var Reader $csvReader */
        $csvReader = ReaderFactory::create(Type::CSV);
        $csvReader->setFieldDelimiter($delimiter);
        $csvReader->open($fileName);

        /** @var Writer $excelWriter */
        $excelWriter = WriterFactory::create(Type::XLSX);
        $tmpExportFile = tempnam("/tmp", "export");
        $excelWriter->openToFile($tmpExportFile);

        foreach ($csvReader->getSheetIterator() as $sheet) {
            foreach ($sheet->getRowIterator() as $row) {
                $excelWriter->addRow($row);
            }
        }

        $csvReader->close();
        $excelWriter->close();
````````

However, it actually gets to closing the writer. I'm not sure how this library works internally (i guess with tmp files).

<img width="940" alt="screen shot 2015-09-30 at 10 57 59" src="https://cloud.githubusercontent.com/assets/6803540/10188767/4ee24a7e-6762-11e5-9fa6-359932b3c906.png">

Any idea how I can process this without increasing the max execution time in php?

**Comment by adrilo** [comment]
Thanks @axelvnk !

Contrary to CSV where you can add easily add data to an existing CSV file (and therefore split the 25k lines into five 5k lines, hence reducing the execution time by 5 for each batch), it's not possible to add data to an existing XLSX file.
XLSX files are basicaly a bunch of XML files describing the data, zipped together. Unfortunately, I don't have a solution to write that much rows into a XLSX file. By nature, writing a lot of rows will take time.

Spout, by default, optimizes the writing process. So unless you explicitely used shared strings instead of inline strings (https://github.com/box/spout#strings-storage-xlsx-writer), there's not much you can't do without increasing the max execution time.
