### ISSUE TITLE
stream_get_line = max 8192 bytes if length == 0

### ISSUE THREAD

**Issue by ivanchenkoandriy** [box/spout#127]
stream_get_line($handle, $length, $ending);
if length === 0 then max bytes = 8192

/vendor/box/spout/src/Spout/Reader/CSV/RowIterator.php
line 150
http://joxi.ru/BLmGBg6HboJkrl

25000 - save the situation

I have very long lines

**Comment by adrilo** [comment]
There is an enhancement proposed to deal with long lines with stream_get_line: https://bugs.php.net/bug.php?id=48421

If you have the time, do you mind creating a pull request to add a new constant containing the max number of bytes. Also instead of a random 25000, I'd keep something consistent with 8192 (=2^13). For instance 16384 (2^14) or 32768 (=2^15).
