### ISSUE TITLE
Writing date

### ISSUE THREAD

**Issue by adrilo** [box/spout#151]
It is currently not possible to pass a DateTime object to a writer, while readers do support dates.

**Comment by dexcell** [comment]
+1

**Comment by iamquan** [comment]
:+1:

**Comment by bevhost** [comment]
I made a workaround for this, since in Excel dates are just a number with a date format for presentation, if you output the right number you can format the column as a date once you load it into Excel and the correct date shows.
I use this  (strtotime($datestr)/86400)+25569.4167
strtotime converts the date string into a unix timestamp which is the number of seconds since 1970.  Excel dates are the number of days since 1900.  There is 86400 seconds in a day and 1970 is 25569 days from 1900.  I use .4167 because I'm in Australia which is GMT+10 hours.

**Comment by adrilo** [comment]
The issue was created as a solution for the "appending data to an existing spreadsheet that contains dates" problem. To append data, one needs to copy the contents of the existing spreadsheet, row by row, and write each row to another spreadsheet before adding new data. This works well in most cases but did not work when cells contain dates: the reader is able to read dates, returning a DateTime object which is not accepted by the writer when trying to copy the row. 

This was before the `setShouldFormatDates` was added though... Now with this option, dates will be returned as strings, which is supported by the writer. So even though the cell type will be incorrect, Excel is usually good enough to detect that it's a date. And visually, the old and new spreadsheet will look exactly the same.

If a developer wants to write a date in another context, then it will be his/her responsibility to format the date before passing it to Spout.

I believe that this approach is a good compromise to avoid adding a ton of complexity to the Writer code to support dates properly. Hence closing this issue.
