### ISSUE TITLE
Invalid handling of long numbers in XLSX

### ISSUE THREAD

**Issue by JSmith01** [box/spout#159]
When library loads long number (f.e. 865640023012945), it is converted to float (in \Box\Spout\Reader\XLSLX\CelllValueFormatter - formatNumericCellValue), and, because of this, number losts its last digits.

In some cases it's completely unacceptable behavior, maybe it's better to return raw string in that case (when is_numeric($val) == true, is_int($val) == false, is_float($val) == false) ?

As I can see, ODS has the same problem, it tries to convert long number to float too (\Box\Spout\Reader\XLSLX\CelllValueFormatter - formatFloatCellValue).

**Comment by adrilo** [comment]
Hey @JSmith01, thanks for filing this issue. This is indeed a valid concern!
Can I ask you what kind of app you are building, using such large numbers? Since PHP won't be able to use this number for arithmetic calculations, how do you plan on using it? Are you using the BC Math extension (http://php.net/manual/en/ref.bc.php)?

**Comment by rafsoaken** [comment]
It may be problematic for all kinds of barcodes.
(I have this problem importing CSV, ODS, XLSX in phpmyadmin into mysql tables).

**Comment by mmorgan57** [comment]
15-digit numbers and longer are often used for inventory serial numbers and shipment tracking numbers (FedEx and USPS). Correcting this bug would be extremely helpful, as would the ability to format a cell to "text" format, since Excel converts long numbers to scientific notation if the cell formatting is not set.

**Comment by adrilo** [comment]
Those are legit use cases. Thanks for chiming in!
I'll try to push a fix soon. Unless someone wants to give it a try. Based on @JSmith01's comment, it does not look to hard to fix.

**Comment by adrilo** [comment]
@JSmith01, @rafsoaken, @mmorgan57 I just pushed a new version (2.4.1) that contains the fix for this issue. Please let me know if it solves your problem.
