### ISSUE TITLE
Feature request: Row count before iterate the sheet

### ISSUE THREAD

**Issue by lamannapov** [box/spout#170]
Is there anyway we can implement the row count on the sheet before we iterate it? Right now, we can only increase the count when iterating the sheet. That would be awesome if we can read the total rows number first to show the progress when reading it.

Thank you!

**Comment by adrilo** [comment]
Hi @lamannapov,

While this can be a great addition, there are some technical limitations to achieve that:
- ODS files don't store the dimension of the spreadsheet. You have to go through the entire XML file to get the number of rows.
- some XLSX files are similar to ODS files and don't store this information. Some other do have it at the top of the XML file so it is accessible before parsing the content.
- CSV files are not straightforward either since a line break inside a text block is valid and does not count as a new row. So we can't simply rely on the number of lines in the file and again, we have to read and parse the whole file before knowing how many rows there are.

Other libraries have chosen to parse the whole file and store all the data and metadata in memory. This is good because you have a lot of information available but this method reaches its limits with large files, where the data to store in memory is too large and consume it all.
Spout, on the other hand, streams the data. This means it goes through the content row by row, only keeping one row in memory. Once the row is read, it is returned and once consumed, it is removed from memory. Such an approach is great for large files, since you'll keep the memory usage constant. But there are several pieces of information that cannot be fetched, such as the number of rows.

I hope that makes sense.

**Comment by sanketin2** [comment]
Currently it's reading all the data in row so looping that for just getting total number of rows would be very slow. If any function that just give us row exists and we increment the counter to getting total rows would be great. Example: "while ($reader->hasNextRow()) { $totalRows++; }"

I am looking this kind of solution for xls/xlsx.

**Comment by symio** [comment]
Hello,
> I am looking this kind of solution for xls/xlsx.

Have you got any good news for us on that idea ?

**Comment by developedsoftware** [comment]
I am trying to get the row count by looping with the rowIterator - would be nice to have a helper function that can do the same thing without filling up the cells array as it goes through the rows. Would be much quicker. Agree that something like what @sanketin2 suggests would be wonderful:

"while ($reader->hasNextRow()) { $totalRows++; }"

**Comment by adrilo** [comment]
I tried to implement a counter for sheets and rows recently. I managed to get something working for ODS and XLSX but was blocked counting "rows" for CSV files. It required large changes for CSV and I was not able to get the whole thing working...
I'll try to post something soon

**Comment by developedsoftware** [comment]
I am quite happy to loop round the rows and increment a counter (after all thats the most efficent way with regards to memory usage). However, when I am doing this I was suprised the row iterator was always filling up the cells object with data from the spreadsheet - which slowed it down massively and is kind of wasteful?

Being able to pass a paramter to the row iterator to say "do not fetch cell values" would allow quick iteration through the rows. 

Or even better - a helper function in the reader class that simply did all of the above when you called getRowCount() would be wonderful!

**Comment by developedsoftware** [comment]
Hi @adrilo,

Am I right in thinking I can just change the row iterator callbacks to prevent the library processing the cell data ? 

`$this->xmlProcessor->registerCallback(self::XML_NODE_CELL, XMLProcessor::NODE_TYPE_START, [$this, 'processCellStartingNode']);`

If I was to set that to false would that essentially allow me to loop the rows without filling up the with cell data? That would probably crack it!
