### ISSUE TITLE
Question about date type

### ISSUE THREAD

**Issue by DMGPage** [box/spout#178]
When read xlsx cell with date value, result is DateTime object. It is fine if I expect date, but what if I expect some string and now I have to validate it. How to get original string, if I don't know original format?

For example if cell contains "31.10.1959" and it is date type, reader result is DateTime object with value "1959-10-31 00:00:00". Problem is that I can not show user that "1959-10-31" is not what I expect, because file contains "31.10.1959". Is there any way how to get original string without DateTime object? Or at least get original format?

**Comment by adrilo** [comment]
If I understand correctly, you have a spreadsheet with some dates in it, but you don't know that they are dates. Therefore when reading all the rows, you currently have to check each value to see if it's a date (as you don't know which cells contain a date in advance) and if so, convert it back to a string.
What you would want instead is a way to disable the automatic conversion from "31.10.1959" to DateTime and have Spout return "31.10.1959".

Is that correct?

**Comment by DMGPage** [comment]
Yes in my case user input date, where he should not and I have to send user error with original value, but I can not do that, because I do not know what was original value. I want option, how to disable automatic conversion and return value (in my example it would be "31.10.1959").

**Comment by adrilo** [comment]
Spout converts the inputted string to a date only if the cell is marked as Date. Having it returned as a string seems like a hack for your use case, as you basically expects the library to return something incorrect (a string instead of a date).
If you expect the cell to contain dates, you should check whether the returned value is a date (if the cell type was set to Date) or a string (if the cell type was not set). If the value is incorrect, you can transform the date back to string if needed (http://php.net/manual/en/datetime.format.php)

**Comment by DMGPage** [comment]
Again it is fine, if I expect date. But if I expect string, I have no use of this DateTime object. And no, I can not transform it back to original string. Yes, it has function "format", but how could I know what was original format? Was it "Y-m-d H:i:s" or "d.m.Y" or may be something else? I can not return to user error "Value '1959-10-31 00:00:00' is incorrect" when original value is "31.10.1959".

**Comment by slickorange** [comment]
I am having a similar issue - I have a field with an integer value but Spout converts it to a DateTime object. Is there any way to turn off this automatic conversion?
I have set the cell to a number in the spreadsheet, but I am converting from OSX Pages to MS Excel, so not sure if that is causing the issue.

**Comment by adrilo** [comment]
Spout only converts a numeric value to a date if its cell type is set to Date. @slickorange I am guessing in your case the conversion does set the type to Date and that's why you end up with a DateTime object.

Anyway, to solve this problem, there need to be a new function added to the Reader API:

```php
$reader = ReaderFactory::create(Type:XLSX);
$reader->disableDateAutoConversion();
OR
$reader->returnDatesAsStrings();
```

The tricky part is to properly format the date. Excel has a million ways to format a date. These formats are stored in the styles.xml file and have each an ID or follow a specific pattern. You then need to look up the corresponding pattern for the date and convert your date to the right format.

@DMGPage @slickorange, are you guys interested to give it a try?

**Comment by slickorange** [comment]
Thanks, I will try it. Luckily I don’t have any dates in my file so I don’t
have to worry about date formatting.
