### ISSUE TITLE
ODS exports doesn't work with associative arrays 

### ISSUE THREAD

**Issue by constant-null** [box/spout#192]
Export to ODS throws 
`ErrorException in Worksheet.php line 147: Undefined offset: 0`
if associative array passed to `addRow` or `addRows` method.

The problem is that elements are accessed using numeric indexes, and since none are present, the error is occurring

    public function addRow($dataRow, $style)
    {
        ...
        for ($i = 0; $i < $cellsCount; $i++) {
            $currentCellValue = $dataRow[$currentCellIndex];
            //                 ^ problem seems to be here ^
            ...
        }
        ...
   }

I am not quite really sure that it is a bug, but any help in solving  this problem will be appreciated.

**Comment by adrilo** [comment]
Hi @constant-null,

To fix this issue, you can call `array_values()` on the row array you're passing to the writer.
I'm hesitant adding this to Spout as it would affect global performance. So I'd rather have every client take care of it so that people not using associative arrays would not be affected.
