### ISSUE TITLE
Can't read cell formatted as "time" in XLSX

### ISSUE THREAD

**Issue by bartoffw** [box/spout#193]
I've found a problem when reading cell values that are formatted as "time". In such case Excel just puts a float value (between 0.0 and 1.0) in the cell that precisely identifies the time of the day.
After some investigation I figured out that the cell is correctly identified as "datetime" format. However, as the value is below 1.0, it gets ignored [here](https://github.com/box/spout/blob/v2.4.3/src/Spout/Reader/XLSX/Helper/CellValueFormatter.php#L192) and returns null.

I have some quickfix for this, which basically treats such value as a "time" value and converts it correctly, but, as I'm not an XLSX format expert, I assume that it won't be correct for all cases.
I can provide a test XLSX file for this if needed.

**Comment by adrilo** [comment]
Hi @bartoffw,

Thanks for filing this issue and starting the investigation!
It seems like we need to be more precise about the cell types. Dates and times have different requirements so instead of identifying a cell as "datetime", we should be able to tell if a cell is "date", "time" or "date+time". This way, we can handle the 0 - 1 edge case properly.

Feel free to submit a pull request if you can !

**Comment by joefreire** [comment]
i'm with same problem, i need get value as time and spout return all time value as null
how i can solve that?

**Comment by bartoffw** [comment]
@joefreire, @adrilo I've just submitted an initial fix for this, for those who need instant solution. As soon as I have some more time I'll think it over and see how the code may be improved.

**Comment by joefreire** [comment]
thank you for you help, works for me
