### ISSUE TITLE
Problem with empty cells

### ISSUE THREAD

**Issue by mirabs** [box/spout#194]
Hi;
I have a problem with empty cells while reading excel sheet.

My file contains 30 columns, usually the last two columns are empty. 
While reading the lines with Spout, the size of a row is either 30 (all cells are extracted) or 28 (the last two empty cells are not included). I need to extract all the columns even the empty ones, where do you think is the problem?
I can send you the file if you need it.

Thanks.

**Comment by adrilo** [comment]
Hi @mirabs,

The dimension of the spreadsheet is not always embedded into the XLSX file. If it is, Spout will be able to read it before parsing the document and fill the row with empty strings if the row has empty cells at the end. However, if it's not, Spout has no idea of the size of the row so it will just ignore the last empty cells.

Also, because Spout uses streaming, you can always move forward. This means that if the 1st row has 28 cells (and 2 empty cells) and the 2nd row has 30 cells, then there is no way to add 2 empty cells to the 1st row after it is read.

I can think of 2 ways to fix your issue:
- If you know the dimension, manually add empty strings to fill your row
- If you have control on the XLSX file, make sure it contains the dimension of the spreadsheet (something like this: `<dimension ref="A1:C4"/>` in the `sheetN.xml` file)

**Comment by mirabs** [comment]
Thanks @adrilo ;
I know the dimension, so I added the empty strings manually.
