### ISSUE TITLE
XLSX reader trims cell values

### ISSUE THREAD

**Issue by madflow** [box/spout#195]
Hello,

I came across the issue, that only the XLSX reader trims the cell values:

```
use Box\Spout\Writer\WriterFactory;
use Box\Spout\Reader\ReaderFactory;
use Box\Spout\Common\Type;

$data = [
    [' A '],
];

// Write Data
$writerXlsx = WriterFactory::create(Type::XLSX);
$writerXlsx->openToFile('test.xlsx');
$writerXlsx->addRows($data);
$writerXlsx->close();

$writerOds = WriterFactory::create(Type::ODS);
$writerOds->openToFile('test.ods');
$writerOds->addRows($data);
$writerOds->close();

$writerCsv = WriterFactory::create(Type::CSV);
$writerCsv->openToFile('test.csv');
$writerCsv->addRows($data);
$writerCsv->close();

// Read files and dump the result
$result = [];
$reader = ReaderFactory::create(Type::XLSX);

$reader->open('test.xlsx');
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        $result['xlsx'][] = $row;
    }
}
$reader->close();

$reader = ReaderFactory::create(Type::ODS);
$reader->open('test.ods');
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        $result['ods'][] = $row;
    }
}
$reader->close();

$reader = ReaderFactory::create(Type::CSV);
$reader->open('test.csv');
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        $result['csv'][] = $row;
    }
}
$reader->close();

var_dump($result);

array(3) {
  'xlsx' =>
  array(1) {
    [0] =>
    array(1) {
      [0] =>
      string(1) "A"
    }
  }
  'ods' =>
  array(1) {
    [0] =>
    array(1) {
      [0] =>
      string(3) " A "
    }
  }
  'csv' =>
  array(1) {
    [0] =>
    array(1) {
      [0] =>
      string(3) " A "
    }
  }
}

```

I believe all readers should behave the same (or similar at the most). What is the correct behavior? trim() or no trim() ?

**Comment by adrilo** [comment]
Hey @madflow, thanks for filing another issue!

I believe the default behavior should be no trim. If you wrote " A " into the file, you should get " A " back. So CSV and ODS have the correct behavior.
Now XLSX should behave the same. After investigation, it seems like the issue only happens with inline strings. When writing shared strings, Spout adds the `xml:space="preserve"` attribute, telling that the cell value should not be trimmed.

Here is where the problem comes from: https://github.com/box/spout/blob/b69e28050bb3c00ec7c2a3c9ebea384f0b5dc905/src/Spout/Reader/XLSX/Helper/CellValueFormatter.php#L121

Unfortunately, I can't remember if `trim` was used on purpose or not. I believe it was to remove line breaks introduced by XML formatting. I have now removed the pretty formatting so I think it's safe to remove the `trim` and provide a unified behavior.

If you want to send me a pull request with the `trim` removed and an associated test, that'd be awesome. Otherwise, I'll take care of it as soon as I can.

**Comment by madflow** [comment]
Hi, I agree with the judgement that CSV and ODS are correct :) 

I can prepare a pull request!
