### ISSUE TITLE
XLSX -file containing only one row offered as HTM in Firefox

### ISSUE THREAD

**Issue by tomikulmala** [box/spout#197]
I have a downloadable (_$writer->openToBrowser($filename)_) XLSX -file that contains only one header row (_$writer->addRow($header_row)_) with columns from A to AP.
This single row file is offered as **HTM-file** ("filename.xlsx.htm") in Firefox and as Excel file ("filename.xlsx") in Chrome.
If I write header 6 times (= 6 rows) Firefox also offers it as Excel file ("filename.xlsx").

I have not had this problem with PHPExcel I used before box/Spout.
box/Spout is a fresh installation (yesterday) via composer.

Tests have been made in Firefox (45.0.1) and Chrome (49.0.2623.110 m).

**Comment by tomikulmala** [comment]
After some more tests with Firefox... A file with 9 rows and columns from A to AA is being offered as HTM-file. But if I add second sheet with one row it's being offered as an Excel -file.

**Comment by adrilo** [comment]
Hmmm, I tried reproducing the issue but it's working fine for me on both Chrome (49) and Firefox (45.0.1) - Mac versions. Here is the code I used:

```php
$writer = WriterFactory::create(Type::XLSX);
$writer->openToBrowser('test.xlsx');
$writer->addRow(['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','aa','ab','ac','ad','ae','af','ag','ah','ai','aj','ak','al','am','an','ao','ap']);
$writer->close();
```

Can you share the code you're using?

**Comment by tomikulmala** [comment]
I tried your data and it too gets offered as HTM in Firefox (Chrome works).

This data is pretty much the same as mine. I had to change the field names, but I do have spaces and parentheses in them. Also tried without, but no change.

`$data = ['a','b','c (fi)','d (en)','e (fi)','f (en)','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','aa','ab','ac','ad','ae','af','ag','ah','ai','aj','ak','al','am','an','ao','ap'];
$writer = WriterFactory::create(Type::XLSX);
$writer->openToBrowser('test.xlsx');
$writer->addRow($data);
$writer->close();`
I'm using Windows 7 Pro.

**Comment by adrilo** [comment]
Hi @tomikulmala,

It turns out a lot of people are complaining about this Firefox's behavior. Someone filed a bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=462915

There are some workarounds though. You can take a look at these links:
- https://support.mozilla.org/en-US/questions/965162
- https://support.mozilla.org/en-US/questions/1052979

Spout is sending the correct mime type for XLSX files so the issue is coming from the mapping Firefox maintains internally. If it things XLSX files are HTML files, then it will add the missing extension and serve you the file with the added extension.

**Comment by tomikulmala** [comment]
Thanks @adrilo! I'll take a look at the links.
