### ISSUE TITLE
Add data to a specific cell

### ISSUE THREAD

**Issue by swaitz** [box/spout#216]
Is there a possibility to add data to a cell and not complete rows?
Something like addCell($data, $rowIndex, $columnIndex)?

I need this to maintain my connection between the header of the excel file and the data of it. We generate the excel from tables which are completly changable by the user. So he can swap cells in such a manner like he want to view his data.

**Comment by adrilo** [comment]
Unfortunately, this is not possible. In order to manage memory efficiently, Spout streams the data you sent it to the output file, one row at a time. This is a one way operation, which means you can't go backwards... So once you've written a row, you can't make any changes to it, nor to the previous rows.

To solve your problem, the only option I see is to do some kind of preprocessing to make sure you have all the information you need before sending data to Spout.
