### ISSUE TITLE
Browser giving "The mysitename.com page isn’t working it didn’t send any data." message

### ISSUE THREAD

**Issue by ranjeet21r** [box/spout#250]
$results = DB::table('table_name')->select($tblcolumnsreal)->orderBy('id', 'desc')->get();

$filename = time() . '_dump_tool_data.csv';
$writer = WriterFactory::create(Type::CSV); // for CSV files
$writer->openToBrowser($filename); // stream data directly to the browser

$writer->addRow($tblcolumns); // add a row at a time
$writer->addRows($results); // $results columns contains about 112780 records

$writer->close();

Above is my code some time it is working properly and gives CSV file to download 
but some time gives Browser giving "The mysitename.com page isn’t working it didn’t send any data." message . i am using this code in Laravel 5.2

**Comment by adrilo** [comment]
Hi,

First, you should probably use an iterator instead of fetching all the records at once and storing that in a variable as this can lead to memory issues :)
Anyways, your code looks good. I quickly googled the issue and it seems like an environment issue that has not much to do with the code. To make sure, you can try reproducing it in other browsers.

If you are able to reproduce the error in other browsers, then this may be due to the program timing out (the max execution time was exceeded). You can try setting it to some longer values (`set_time_limit(0)`) and see if that's better.

Hope that helps!
