### ISSUE TITLE
CSV reader does not encode to UTF-8?

### ISSUE THREAD

**Issue by romulo-rocha** [box/spout#274]
I am not sure if it has to do with the CSV file I am opening or if it's really a problem with Spout, but the CSV reader is not displaying UTF-8 encoded content on the screen. I have, for example, a cell with the following content: "**_Código_**". When I print the row on the screen I get "C♦digo".

I had to come up with a work-around in order to display it propely encoded:
```
  function encode_items (&$item, $key) {
    $item = utf8_encode($item);
  }
  foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
      array_walk_recursive($row, 'encode_items');
      echo '<pre>';
      print_r($row);
      echo '</pre>';
    }
  }
```
Here's the entire code:

```
<?php
  set_time_limit(18000);
  require_once('./spout-2.5.0/src/Spout/Autoloader/autoload.php');
  use Box\Spout\Reader\ReaderFactory;
  use Box\Spout\Common\Type;

  function encode_items (&$item, $key) {
    $item = utf8_encode($item);
  }

  $reader = ReaderFactory::create(Type::CSV);
  $reader->setFieldDelimiter(';')
         ->open('./teste.csv');

  foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
      array_walk_recursive($row, 'encode_items');
      echo '<pre>';
      print_r($row);
      echo '</pre>';
    }
  }
  
  $reader->close();
```

It works properly, now. But is this how it is supposed to be? Where did I get it wrong?

**Comment by adrilo** [comment]
Hi @romulo-rocha,

The problem comes from the fact that the encoding of the file and the encoding used by PHP are different (PHP is UTF-8, while the file seems to be ISO-8859-1). BTW, `utf8_encode` is a terrible name as what it does is convert a string to UTF-8 from ISO-8859-1 **only**.

Spout does not magically detect the encoding of the file read. You have to explicitly tell it. Unfortunately, it does not support ISO-8859-1 so you'll have to do the conversion yourself. Your code looks right then. Alternatively, if you know the encoding of the file, you can convert the file to UTF-8 before reading it with Spout.

Hope that helps!
