### ISSUE TITLE
Not possible to save multiple files

### ISSUE THREAD

**Issue by quantuumsnot** [box/spout#277]
```
for ($i = 0; $i < 5; $i++) {
   $file =  __DIR__ . "/" . ($i+1) . ".xlsx";
   $writer->openToFile($file);
   $writer->getCurrentSheet()->setName((string) ($i+1));
   for ($j = 0; $j < 100; $j++) {
     $row = range(($j*10)+1, ($j+1)*10);
     $writer->addRow($row);
   }
   $writer->close();
}
```
The error: 

> fwrite(): supplied resource is not a valid stream resource in D:\www\phptablegen\spout\src\Spout\Writer\XLSX\Internal\Worksheet.php on line 165
Fatal error: Uncaught Box\Spout\Common\Exception\IOException: Unable to write data in D:\php\temp/xlsx578aa2665a2404.90908599/xl/worksheets/sheet1.xml in D:\www\phptablegen\spout\src\Spout\Writer\XLSX\Internal\Worksheet.php:167

If I change $file to be `$file = fopen("php://memory", "w+b");` there's a different error:

> Warning: fopen() expects parameter 1 to be a valid path, resource given in D:\www\phptablegen\spout\src\Spout\Common\Helper\GlobalFunctionsHelper.php on line 25 Fatal error: Uncaught Box\Spout\Common\Exception\IOException: File pointer has not be opened in D:\www\phptablegen\spout\src\Spout\Writer\AbstractWriter.php:158

It manages to save only 2 of 5 - one with the data and the second one has 0 size which cannot be opened

PHP 7.0.6 x64 TS
Windows 7 x64

**Comment by adrilo** [comment]
Hi @quantuumsnot,

Your 1st error is due to the fact that the Writer needs to be recreated if you close it. Doing this works:
```php
for ($i = 0; $i < 5; $i++) {
   $file =  __DIR__ . "/" . ($i+1) . ".xlsx";
   $writer = WriterFactory::create(Type::XLSX);
   $writer->openToFile($file);
   $writer->getCurrentSheet()->setName((string) ($i+1));
   for ($j = 0; $j < 100; $j++) {
     $row = range(($j*10)+1, ($j+1)*10);
     $writer->addRow($row);
   }
   $writer->close();
}
```

Regarding your 2nd error, openToFile expects a file path. You gave it a `resource`. If you try instead with `writer->openToFile('php://memory');`, it will work as expected.

Hope that helps!

**Comment by quantuumsnot** [comment]
Thanks, missed that. The problem is that there's no documentation, at least I didn't found

Speaking for it have another question. If I put these lines in a function:
`require_once dirname(__FILE__) . '/spout/src/Spout/Autoloader/autoload.php';
  use Box\Spout\Writer\WriterFactory;
  use Box\Spout\Common\Type;`

I'm only receiving: 
> Parse error: syntax error, unexpected 'use' (T_USE) in ...

Is there a way to load the library in function's scope or it always must be in the global?

**Comment by adrilo** [comment]
`use` should be at the class level. You can't have `use` in a function.

The autoloader is a lazy autoloader which means the classes for Spout will only be loaded when used. Using `use` does not load the class, it just creates an alias so that you can do `WriterFactory::create()` instead of `Box\Spout\Writer\WriterFactory::create()`. It makes the code be more readable.

**Comment by quantuumsnot** [comment]
I hate OOP. I can read it, but I hate it :\
