### ISSUE TITLE
How to improve performace

### ISSUE THREAD

**Issue by joefreire** [box/spout#292]
Hi, I have a large excel file and i want only read it but is so slow more than 20min
you can help me?

**Comment by adrilo** [comment]
Hi! How big is your file? How many rows and columns?

Spout is already optimized for fast reads, there's not much more you can do. If the file is very large, it is normal that going through the whole file takes time. There are some performance metrics in the README if you want to compare.

One optimization you could do is to make sure the file you're reading uses inline strings (instead of shared strings). If you control the creation of this file, this is something you can do. Otherwise, there are no secret options to optimize Spout further.

**Comment by adrilo** [comment]
@joefreire?

**Comment by adrilo** [comment]
[CLEANUP] Closing issue - no response for 2 months
