### ISSUE TITLE
libxml_disable_entity_loader and Spout

### ISSUE THREAD

**Issue by IamFake** [box/spout#293]
Hi there.

When i use libxml_disable_entity_loader(true) and trying to open xlsx file - i get an error "Unable to open source data", but setting libxml_disable_entity_loader to false is not an option (in my project anyone can load xlsx with prices). I've read in some issues here that it's php bug and nothing can be done here. But, Spout has custom XMLReader class that extends original XMLReader, so why not overload the "open" method?

```php
public function open($URI, $encoding = null, $options = 0)
{
	$file = file_get_contents($URI);
	return $this->XML($file, $encoding, $options);
}
```

That works for me.

p.s. sorry for my eng :)

**Comment by adrilo** [comment]
Using `file_get_contents` loads the entire content of the XML file in memory. While this works with small files, it does not with larger ones. That's usually what other libraries do though (PHPExcel for instance) and the reason why they can't support large files.
Spout was built to solve this problem and instead of loading the whole XML file in memory, its content is streamed so that only one row at a time is stored in memory. Therefore no matter how big the file is, the memory consumption remains constant.

Hope that answers your question.
