### ISSUE TITLE
how to delete a sheet ?

### ISSUE THREAD

**Issue by mrhaytham** [box/spout#298]
Hi there,

thanks for this great library ! I have a problem dealing with sheets, I couldn't find a way to delete sheets when writing a new xlsx file.

the only methods to handle sheets are addNewSheetAndMakeItCurrent() and getCurrentSheet(). How about deleting a sheet ?

Thanks.

**Comment by adrilo** [comment]
Hi @mrhaytham,

Deleting a sheet is not as simple as calling `deleteSheet(1)`. This is because Spout reads the spreadsheet content row by row, as opposed to load its entire content in memory.
So if you want to delete a sheet, what you need to do is something similar to what's described here: https://github.com/box/spout/wiki/Edit-an-existing-spreadsheet

In your case, you'll have a condition on the `$sheetIndex` or sheet name: `if ($sheetIndex === 1) { continue; }` will "delete" sheet 1.

So deleting a sheet actually means, rewriting the content of all the other sheets, and skipping the "deleted" sheet.

Hope that helps!

**Comment by mrhaytham** [comment]
thanks, actually that was helpful
