### ISSUE TITLE
In AbstractMultiSheetsWriter::getSheets() have the ability to return an associative array of Sheet Name => Sheet

### ISSUE THREAD

**Issue by Neo-Desktop** [box/spout#308]
This  change is exclusive to formats with multiple worksheets (XLSX, ODS).

As a developer, I would like an associative array of 'sheet name' => sheet for sheets in a workbook.

The externalSheet array in AbstractMultiSheetsWriter::getSheets() could fetch the name for the associative value prior to calling getExternalSheet().

This change would add negligible memory overhead.

**Comment by adrilo** [comment]
Hi @Neo-Desktop!

I don't really like the idea of having an API that's not self documented. With your proposal, how can someone guess that `getSheets` returns an associative array where keys are the sheets name? Autocompletion cannot help you in this case (and that's why we're trying to not have public APIs return associative arrays).

The current approach (`getSheets()` and `$sheet->getName()`) does require 2 separate calls but it has the advantage of being discoverable and consistent with the rest of the code.

**Comment by Neo-Desktop** [comment]
Ah, roger that. Thanks for the input!
