### ISSUE TITLE
Please allow cell objects in addRow() methods so that parts of a cell can be styled

### ISSUE THREAD

**Issue by cmanley** [box/spout#325]
PHPExcel has a class like that called PHPExcel_RichText that can be assigned to a cell, instead of just scalars:
http://stackoverflow.com/questions/8045056/phpexcel-how-to-make-part-of-the-text-bold

**Comment by adrilo** [comment]
This is a really complex task, for the streaming approach that Spout takes. Having rich text requires keeping track of the cell content as well as its style. As you may have noticed, Spout does not support cell styling (and support row styling instead) because of the complexity it adds and the additional memory it would need to store the data.

For the v3 of Spout, we're planning to add per cell styling. But most likely, styling part of the cell won't be supported :(
