### ISSUE TITLE
normalizing how empty cells are handled

### ISSUE THREAD

**Issue by Gavrisimo** [box/spout#332]
So I had a weird issue I had to fix today, seems some xlsx files don't have some info about the number of columns in them, meaning depending on the reader I would get different number of columns in each row.

For example, when using CSV I would always get 36 columns, but when using XLSX I would sometimes get 35 columns and sometimes 34 columns...

I did find some issues mentioning this and the answer was something like fill in those empty columns yourself. So I did:

```php
    public function getFileData()
    {
        $this->reader->open($this->path);

        $data = [];

        foreach ($this->reader->getSheetIterator() as $sheet) {
            foreach ($sheet->getRowIterator() as $row => $values) {
                $data[ $row ] = $values;
            }
        }

        /*
         * Workaround for Spout sometimes ignoring empty columns on far right
         * meaning, for example, some rows end up with 36 columns and some with 34
         *
         * We need to fill those empty ones.
         */
        $minColumnsCount = count(min($data));
        $maxColumnsCount = count(max($data));

        if ($minColumnsCount !== $maxColumnsCount) {
            foreach ($data as $row => $columns) {
                $numberOfColumnsInRow = count($columns);

                if ($numberOfColumnsInRow !== $maxColumnsCount) {
                    $data[ $row ] = $columns + array_fill($numberOfColumnsInRow, $maxColumnsCount - $numberOfColumnsInRow, '');
                }
            }
        }

        return $data;
    }
```

So I am wandering if this is something that can land in spout as an opt in setting, or maybe even make it enabled as default.

My main reason for this is just consistency, when dealing with PHP representation of csv/xlsx files to me it is sooo very helpful that I know those representations are always the same, no matter what type extension is used. Again, when using CSV, this file of mine is always going to have 36 columns, it just does not make sense to have XLSX file that is not behaving the same, especially since the fix is super simple.

Thoughts?

**Comment by adrilo** [comment]
@Gavrisimo this is a known problem and here is why we can't fix it:
In the XML describing the sheet, there is a "dimension" **optional** section that can tell what the most far right column is (something like "A1:E4"). This is used by Spout to fill rows that have less than 5 (*E = 5 columns*) cells defined.
However, since this section is optional, if not defined Spout has no idea how many cells it should add. And because rows are read one by one, there is no way to tell in advance what which row has the max number of columns so in this case, Spout just returns the data it sees.

If you know in advance that you expect 10 columns, you can add an `array_fill`, otherwise you'll have to do what you did.
