### ISSUE TITLE
Numbers and Booleans in DB recordset handled as strings

### ISSUE THREAD

**Issue by slewitan** [box/spout#351]
I am passing entire DB recordsets to the addRowWithStyle function

	while ($row = oci_fetch_assoc($stid));
		$writer->addRowWithStyle($row, $style); 
and the entire row even the numbers and Booleans have an object type of string.

I rewrote the CellHelper functions to detect what is really a number or Boolean. 
src/Spout/Writer/Common/Helper/CellHelper.php lines 62 - 90

    /**
     * @param $value
     * @return bool Whether the given value is a non empty string
     */
    public static function isNonEmptyString($value)
    {
		if(is_numeric($value) || CellHelper::isBoolean($value))
			return false;
		return (gettype($value) === 'string' && $value !== '');
    }

    /**
     * Returns whether the given value is numeric.
     *
     * @param $value
     * @return bool Whether the given value is numeric
     */
    public static function isNumeric($value)
    {
		return is_numeric($value); 
    }

    /**
     * Returns whether the given value is boolean.
     * "true"/"false" and 0/1 are not booleans.
     *
     * @param $value
     * @return bool Whether the given value is boolean
     */
    public static function isBoolean($value)
    {
		switch (strtolower($value))
		{
			case 'true':
			case 'false':
				return true;
			default:
				return false;	
		}	
    }

in src/Spout/Writer/XLSX/Internal/Worksheet.php I need to also change line 210

        } else if (CellHelper::isBoolean($cellValue)) {
            $cellXML .= ' t="b"><v>' . (strtolower($cellValue)=='true'?1:0) . '</v></c>';
I don't know if this is the best way to deal with it but it worked for me.

P.S.
is_bool didn't work.
I'm running PHP Version 5.6.0

**Comment by adrilo** [comment]
@slewitan, this issue is specific to your use case. You want "5" to be written as a number but some people may want that to be written as a string. Same goes with "true"/"false".
Changing the code how you did it means that you can no longer write "5" as a string. With the current implementation, it's up to the developer to convert this "5" to an int to have it written as a number or leave it as is to have it written as a string.

I believe that the current implementation covers more use cases so I'll leave it as is.
