### ISSUE TITLE
'Cannot perform I/O operation outside of the base folder: C:\Windows\Temp'

### ISSUE THREAD

**Issue by badcom** [box/spout#355]
Hello,
First off, thanks a lot for the library!

I've run into the below issue:

I'm reading an excel file with over 100k rows and when it's lasting about 5k rows I get the below error. I've tried it with a smaller file with the same result.

`PHP Fatal error:  Uncaught exception 'Box\Spout\Common\Exception\IOException' with message 'Cannot perform I/O operation outside of the base folder: C:\Windows\Temp' in C:\inetpub\wwwroot\keepcon\vendor\box\spout\src\Spout\Common\Helper\FileSystemHelper.php:130`

What do I need to do to fix this?

**Comment by badcom** [comment]
FYI, I upgraded my PHP Server from 5.4.15 to 7.0.12 and that solved the problem.

**Comment by adrilo** [comment]
Not sure why it happened in the first place. Seems like an environment specific issue.
Closing this issue since it's now resolved.

**Comment by creolis** [comment]
I hate to be the guy that resurrects a dead issue, but in this case I have something to add ;-)

Today I debugged the same issue on linux and found out that you're using sys_get_tmp_dir() in order to retrieve a temporary path to store arbitrary data while exporting xlsx etc. sys_get_tmp_dir() was not configured on our infrastructure, pointing to /tmp (which was definitely not allowed on a shared-hosting system) and therefore spout died in a fire.

I propose to change to get_temp_dir() in wp-includes/functions.php, since this function respects the WP_TEMP_DIR static, which a user may set in wp-config.php in order to override sys_get_tmp_dir().

This has a massive impact on usability for people on shared-hosting systems, where the hoster did not configure the sys_temp_dir variable correctly and won't do so off the cuff, and also comes with a number of fallback choices made by wordpress in order to get the data stored "wherever it finds writable space" :)

all the best,

/)/)

**Comment by adrilo** [comment]
Hi @creolis, thanks for your input and the time you spent debugging!

> I propose to change to get_temp_dir() in wp-includes/functions.php

I supposed that you're talking about a Wordpress function. Can you please give more details about that? Maybe a link?

Thanks!

**Comment by creolis** [comment]
ah DAMN it... I'm so sorry I bothered you.

Okay, thing is - you're right, it's a wordpress function, and you might ask yourself, why it matters to you. 

Answer is: it does not. I came here because a wordpress plugin that exports XLS had the problem that it died horribly since it always pointed to /tmp, no matter what directory you told wordpress to use. I did not understand why you guys use sys_get_tmp_dir() since wordpress comes with its own version (get_temp_dir()) that takes care of "things" (TM).

Well - turns out the XLS export plugin just uses your framework. YOU of course have no idea that you're part of a wordpress scenario all of the sudden, therefore, you're out of the loop here and did everything right.

Never mind :-)


/)/)
