### ISSUE TITLE
Ability to writing in PHP streams

### ISSUE THREAD

**Issue by zhukovra** [box/spout#378]
When I writing XLS or CSV just for attach it to email in our reporting actions, I don't need in temporary files with sheets contents. At now I can achieve that with output buffering like that:
```php
ob_start();
$writer->openToBrowser('php:/output');
// some writer actions
$writer->close();
$file = ob_get_clean();
```
But it unusable, when you send something to `php:/output` before (like logging messages in console command).

It is useful to have a writing and reading ability for various [PHP streams](http://php.net/manual/en/wrappers.php.php), like `php://memory` and `php://temp`.
```php
$writer->openToResource('php:/temp');
// some writer actions
$file = $writer->close();
```

**Comment by adrilo** [comment]
@zhukovra When working with XLSX or ODS files, temporary files are necessary. This is because of how the file is constructed. XLSX and ODS files are made of a bunch of XML files, zipped together into a single archive. To be able to create this archive, you first need to create all the XML files that go in it and therefore need to store them on disk (hence the temp folder).
This is not true for CSV files though, as you can stream the data directly to the browser if needed.

Now regarding PHP streams, they should be supported. See the code for it here: https://github.com/box/spout/blob/3a330debb366396e4e384a7c113226f827240d80/src/Spout/Reader/AbstractReader.php#L112

It's possible that php://memory does not work because you can only store small files in there but the other wrappers should work. Let me know if it does not.
