### ISSUE TITLE
Having problem read from non UTF-8 file

### ISSUE THREAD

**Issue by ahmetkemall** [box/spout#382]
Hello,

I can read utf-8 files perfectly 
Although  having problem with reading non utf-8  '.csv' files and having problem with some characters.

Here is what i have tried:

```
$reader->setEncoding('UTF-16LE');
$reader->setEncoding('UTF-8');
$reader->setEncoding('CP1252');
$reader->setEncoding('ANSI');
... etc.
```

Complete Code:

``` 
$reader = ReaderFactory::create(Type::CSV); // for CSV files
    $reader->setFieldDelimiter($workSheetIndex);
    $reader->setEncoding('UTF-16LE');
//            $reader->setFieldEnclosure('@');
//            $reader->setEndOfLineCharacter("\r");
    $reader->open($file["path"]);

    foreach ($reader->getSheetIterator() as $sheet) {
        foreach ($sheet->getRowIterator() as $row) {
            $columns = $row;
            break;
        }
        break;
    }
    $reader->close();
```

Thank you..

**Comment by adrilo** [comment]
Hi @ahmetkemall,

Spout only supports a few encodings for CSV files that you can find here: https://github.com/box/spout/blob/30aa1b87e25a04fa2e223efee19c8f0348611cb2/src/Spout/Common/Helper/EncodingHelper.php#L16

It's important that you know the encoding of your file before you give it to Spout, as it can't be guessed. If you used all the options, then the encoding actually used is probably different than the supported ones...

Otherwise your code looks good!

**Comment by ahmetkemall** [comment]
I have tried   $reader->setEncoding('Windows-1254'); 
And I have no more problem for Turkish characters.

Hope helps to someone..

**Comment by NguyenXuanNam** [comment]
![image](https://user-images.githubusercontent.com/14059073/84333835-050a0c00-abbb-11ea-9a86-5bf593379fec.png)
I have tried $reader->setEncoding('Shift_JIS') but it didn't work. 
Can I help you.
