### ISSUE TITLE
Missing support for getActiveSheet

### ISSUE THREAD

**Issue by lijupm** [box/spout#386]
Libraries like PHPExcel has 'getActiveSheet' method which can get you the active sheet(the sheet which is opened) from your workbook.

It would be better if we have something like the following to get active sheet easily

`$sheet = $reader->getSheetIterator()->getActiveSheet();`

**Comment by adrilo** [comment]
Hi @lijupm, I think that's a good idea.
I left some comments on your pull request as it can't be merged as is.

**Comment by adrilo** [comment]
@lijupm It turns out it is not possible to add a `getActiveSheet()` method for ODS files (or rather no way that would not be incredibly slow). So instead, I implemented a `isActive()` method on the `Sheet` object. You can't get the active sheet directly and still have to use a foreach loop, but you now have a way to know if the current sheet was the active one.
