### ISSUE TITLE
Spout Documentation

### ISSUE THREAD

**Issue by Preston-HackSpace** [box/spout#39]
I would like to give spout a try, but I don't know where to start or what functionality is available. Is there a documentation page?

Thanks

**Comment by adrilo** [comment]
The documentation is the README. Copy/pasting the given examples should be a good start.
Because it uses streaming (in order to read/write files with millions of rows), it is not possible to read/write cell by cell or go backwards. This means that you can only read/write row by row, and once a row is read/written, you won't be able to change it again.
Also, cells only support basic values such as numbers or strings. No formulas.

These limitations are compromises to achieve high-speed, memory efficient reads and writes.
