### ISSUE TITLE
$reader->open($filename) takes all the time

### ISSUE THREAD

**Issue by dsiddiqui** [box/spout#40]
I am trying to read a very large excel file, having multiple sheets, in which two or more sheets contain more than 600K records with columns ranging from A to AD.

When I run your sample code of going through each sheet one by one and and iterating through all the rows the program never came back.

I commented all the code and leaving the call to open function, it still takes the same time. Is there a way around of skipping this opening time?

**Comment by adrilo** [comment]
@dsiddiqui When calling open() on a XLSX file, the file containing shared strings is being parsed. This file basically contains all the strings of your sheets. Given the number of rows/columns you have, this is definitely the longest step of the whole process.
Even if we move this step outside of the open() function, it has to be done at one point. So moving it would just shift the problem.

One way to get better performance would be to use inline strings instead of shared strings. If you also use Spout to create your original file, that's the default option. It will totally eliminate this very long step and will be a big performance gain.
If you don't have the control on this original file, the only thing you can do is wait... You are dealing with a HUGE file, so it's normal if it takes ~ 1 hour to be processed.
