### ISSUE TITLE
MSSql import problem (.xlsx)

### ISSUE THREAD

**Issue by ahmetkemall** [box/spout#403]
Hello,

I'm having a problem when i'm trying to import an .xlsx file, that is i wrote with spout.
I'm guessing it's encoding problem,
I there anyway to set up writer's encoding?

Or any ideas what is the problem is ?
Error is attached ..
![2017-03-28](https://cloud.githubusercontent.com/assets/6723855/24412737/f60117fe-13e1-11e7-87d3-be182733dfd0.png)

**Comment by adrilo** [comment]
I don't know exactly what the problem is but you're right, it may be an encoding issue.
XLSX files are always encoded in UTF-8. Maybe your DB is using a different encoding? If so, there may be an option in your import process to specify if the data needs to be converted.

Unfortunately, I won't be able to help more as this is an integration related issue.
