### ISSUE TITLE
Issue in a date format in excel reader

### ISSUE THREAD

**Issue by anilkumar-isol** [box/spout#444]
Hello there,

I'm using this library to read csv and xlsx files. This is working like a charm but at some points this is not formatting datetime values. 

If any cell has "01/01/2017" as value then this is giving error like "Catchable fatal error: Object of class DateTime could not be converted to string in /path/to/file.php on line 32"

if any cell has "**'01/01/2017**"(with a single quote at starting) as value then this is working fine.

Is there any workaround to skip or ignore this issue?

**Comment by anilkumar-isol** [comment]
Hello @adrilo , I have resolved that issue by changing in Spout/Reader/XLSX/Helper/CellValueFormatter.php file in following functions

1. "formatExcelTimestampValueAsTimeValue"
2. "formatExcelTimestampValueAsDateValue" 
 
in those functions I'm returning a string of date/time instead of datetime object. Please check that issue and let me know if I have done right?

**Comment by adrilo** [comment]
Hi @anilkumar-isol !

A cell containing "01/01/2017" and formatted as a date will be converted to a DateTime object, unless you configured the reader this way `$reader->setShouldFormatDates(true);`.
It seems like the exception you are referencing is coming from your code and not from Spout (right?). This is because you are trying to use a DateTime object as a string. If your goal is to get a string back, use `$reader->setShouldFormatDates(true);` before actually reading your file.

Please let me know if that helps!

**Comment by anilkumar-isol** [comment]
Thanks @adrilo for letting me know about "setShouldFormatDates(true)" function. Actually I have been using spout only for the last 3-4 days and I don't know its all functionality.

Thanks again for your support.

**Comment by adrilo** [comment]
Feel free to take a look at the docs to learn about the other tricks :) http://opensource.box.com/spout/getting-started/
