### ISSUE TITLE
Append an existing XLSX file

### ISSUE THREAD

**Issue by JiSoft** [box/spout#454]
Hi, there.
First thank you for nice implementation !

I tried update an existing xlsx file, but Spout has created a new one.
I can see than another people met this problem as well. For instance http://opensource.box.com/spout/guides/add-data-to-existing-spreadsheet/

Is it possible to implement native appending without copy-pasting existing rows ?

**Comment by adrilo** [comment]
Hi @JiSoft,

In order to do that, you need to overwrite some parts of the XML files describing the spreadsheet: the XML for the spreadsheet structure, the one where cell data is stored, the one where styles are stored. Because you can't just append new data to these XML files (you need to write new data to a specific location), this becomes really tricky...
So I don't think it's worth spending some time trying to adapt the current approach to make editing work better. But if you feel like it, you can definitely give it a try! A lot of people would be interested!!
