### ISSUE TITLE
XLSX reader performance

### ISSUE THREAD

**Issue by Gavrisimo** [box/spout#456]
Hey there,

so I've been using box/spout for csv and xlsx files and LibXL for xls files. I'm seeing this one weird issue while reading "bigger" xlsx files(1600rows), where it takes about 5 seconds to go through this code:

```
        foreach ($this->reader->getSheetIterator() as $sheet) {
            foreach ($sheet->getRowIterator() as $row => $values) {
                $data[$count][$row] = $values;
            }

            $count++;
        }
```

When spout is reading csv file it takes like 0.1 - 0.2 seconds and when LibXL is reading the xls file it takes about the same time as the csv file.

To sum up, different file types:

1. csv with spout - 0.13 sec
2. xls with LibXL - 0.04sec
3. xlsx with spout - 5.4sec

So the file data is absolutely same across those different file types, no functions are used(to my knowledge)...

@adrilo I'd love to debug this further, I just need some pointers as to where to start looking... Like which file/function, etc... :) I can't share this file, but I'll try to create one with dummy data and see how it behaves.

**Comment by Gavrisimo** [comment]
Oh I've managed to create some test files, csv and xlsx with 10000 rows. You can download them here: [test.zip](https://github.com/box/spout/files/1224646/test.zip)

1. csv with spout - `0.34418606758118` seconds
2. xlsx with spout - `7.9724202156067` seconds

**Comment by adrilo** [comment]
Hey @Gavrisimo,

There are a few reasons why reading this file is slow. Compared to CSV, the structure of an XLSX file is much more complex, with a combination of multiple XML files that need to be read at the same time. Moreover, the specific file you tested uses shared strings (to optimize file size by reusing duplicate strings) which is slower than inline strings (where cell data is stored in the same file as spreadsheet structure). This requires to keep track of which string is associated to which cell (so slower than just a sequential read). In addition to that, the file uses a lot of shared strings (> 30,000). Spout has a very safe approach to how it deals with memory and it's very likely (depending on how much memory PHP can use) that Spout uses an on-disk caching (instead of in-memory caching, which is much much faster).

Finally, LibXL is a PHP extension that allows it to be written in C++. C++ is much faster than PHP! XLS files are also simpler to parse than XLSX files, so that's another reason why Spout can't compete on speed. But it has other advantages :)

**Comment by Gavrisimo** [comment]
@adrilo so this is expected behavior/speed? Is there any way this could be made faster? :)

**Comment by adrilo** [comment]
Yes, this is expected. There could be several ways to make it faster:
- if you control the creation of the XLSX file, make sure to use inline strings and not shared strings
- if you can't, increase the amount of memory allocated to PHP (this will force Spout to use in-memory caching)
- if you can't, you can manually change this line: https://github.com/box/spout/blob/30aa1b87e25a04fa2e223efee19c8f0348611cb2/src/Spout/Reader/XLSX/Helper/SharedStringsCaching/CachingStrategyFactory.php#L40. Change `12` to `6` for example.
