### ISSUE TITLE
Inconsistent interface

### ISSUE THREAD

**Issue by nCrazed** [box/spout#50]
### Problem

As it stands the return type of `ReaderFactory::create()` method is `XLSX` while it can return both `CSV` and `XLSX`. Additionally `XLSX` defines methods (`hasNextSheet()` and `nextSheet()`) that are not present in neither `CSV` nor `ReaderInterface` 

### Proposed Solution

1. Change the return type of `ReaderFactory::create()` to `ReaderInterface`
2. Add the missing methods to the `ReaderInterface`
3. Implement the new interface methods in the `CSV` class as empty methods.

The method implementation (3\.) could be made at the `AbstractReader` level, but since `csv` is likely to be the only supported format that has no sheets it makes more sense to keep the sheet-less implementation at the `CSV` level.

As far as I am aware

### Usage Example

Here's an example function that seamlessly process CSV and single-sheet XLSX files:
```php
function processSpreadsheet(\Box\Spout\Reader\ReaderInterface $reader, $filePath)
{
    $reader->open($filePath);
    if (method_exists($reader, 'hasNextSheet')) { // don't want to check for concrete type in case more formats are implemented
        $reader->nextSheet();
    }

    processRows($reader);

    $reader->close();
}
```

With the described changes the above function can be simplified to this:
```php
function processSpreadsheet(\Box\Spout\Reader\ReaderInterface $reader, $filePath)
{
    $reader->open($filePath);
    $reader->nextSheet(); // XLSX reader will select the first sheet, CSV reader will do nothing

    processRows($reader);

    $reader->close();
}
```

**Comment by nCrazed** [comment]
Should I go ahead with a pull request for this or wait until we've discussed alternative solutions?

**Comment by adrilo** [comment]
Hey @nCrazed,

Thanks for bringing that up. This is something I hesitated a long time before settling on the current interface. The reason it's as it is is because it feels wrong to add the notion of sheet in the CSV reader. So I moved the sheet related functions into the XLSX part.
Something I could do is add another interface (SheetInterface) that extends the base interface and adds the `hasNextSheet()` and `nextSheet()` functions. This would make it clearer that those functions are available.

The other reason is that the XLSX reader also defines other custom functions (setters mostly) that the CSV reader doesn't define. Unless I moved them to a generic setter `setOptions` - which I don't like because parameters are passed in as array, in a non explicit manner - we'll have to keep custom functions on the reader level.

Now, it would still be great to have the same code to process any kind of documents. This means that the code to read CSV should also be:

```
while ($reader->hasNextSheet()) {
    $reader->nextSheet();

    while ($reader->hasNextRow()) {
        $row = $reader->nextRow();
        // do stuff
    }
}
```
where `hasNextSheet()` returns true the first time and false otherwise. `nextSheet()` can return whatever.
I'm still unsure that this is a better solution as long as Spout only supports 2 formats...

Something else we can consider is using actual iterators instead of the hasNext(), next() pattern:
```
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
       // do stuff
    }
}
```

Thoughts?

**Comment by nCrazed** [comment]
> The reason it's as it is is because it feels wrong to add the notion of sheet in the CSV reader. 

Is it really that wrong to treat csv as a spreadsheet format that happens to always has exactly one sheet?

> The other reason is that the XLSX reader also defines other custom functions (setters mostly) that the CSV reader doesn't define.

Are you sure that this isn't the other way around? I see no new methods on the XLSX reader other than the two sheet related ones. While CSV reader defines `setFieldDelimiter()` and `setFieldEnclosure()`. 

Is there a use case for calling these after rows have been read? In my opinion it's best to limit the choice of delimiter and field enclosure to construction time of the reader object so that only the caller of `ReaderFactory::create()` needs to know the concrete type of the reader. Although I am unsure about how to best pass these options to the factory.

>  Unless I moved them to a generic setter setOptions - which I don't like because parameters are passed in as array, in a non explicit manner - we'll have to keep custom functions on the reader level.

While I share your view on options arrays, it is the way that the named parameters are implemented by the PHP community due to the absence of support for them at the syntax level. Since it is a common practice (at least within PHP) and it's likely to stay that way for a while (until [this](https://wiki.php.net/rfc/named_params) or an alternative RFC is approved) it should be at least considered.

**Comment by nCrazed** [comment]
Just noticed #49 which defines another custom method on the XSLX reader. It appears to be another construction time option which should not be exposed by the ReaderInterface.

At this point it is worth considering modifying `ReaderFactory::create()` to something like this:
```php
public function create($readerType, array $options = [])
{

    // $reader = ...

    $this->setOptions($reader, $options);

    // other construction logic
}

protected function setOptions(ReaderInterface $reader, array $options)
{
    foreach ($options as $option => $value) {
        $method = $this->optionMethodName($option)
        if (method_exists($reader, $method)) {
              $reader->$method($value);
        }
    }
}

protected function optionMethodName($option)
{
    return // logic for converting valid option to "setOptionType" string
}
```

**Comment by Lewiscowles1986** [comment]
I feel that this is not the best fit for the reasons @adrilo mentions with confusion, and lack of multiple sheets support in csv. 

Some file-formats don't have sheet support, so perhaps the interface could be implemented for the core, with a trait, or abstract class, or base class spreadsheet that implements sheets? (inheritance doesn't have to balance)

SO 

* ReaderInterface
  * CSV
  * Spreadsheet
    * XLSX

How well would that fit into this plan?

**Comment by nCrazed** [comment]
Perhaps I should've title the issue a leaky abstraction. While any non-trivial abstraction is bound to be leaky to some degree, the interface of a reader is quite simple and most of its leaks can be addressed.

My primary concern is that as it stands, the `ReaderInterface` serves no purpose. Its consumers need to know the exact underlying implementation to correctly interact with it.

Now, let's see if I can address your concerns in a more clear manner. Keep in mind that all of these are purely in the context of the reader.

### csv file format does not support multiple sheets.
Yes, it doesn't support **multiple** sheets, but within the context of this library it is a primitive spreadsheet  format that supports exactly one sheet. i.e. it has a single set of rows and columns.

This is why I disagree with the following:
> it feels wrong to add the notion of sheet in the CSV reader

The fact that it supports only one sheet is an implementation detail and should be no concern of the interface or its consumers.

### Some file-formats don't have sheet support
I argue that any format that can not be interpreted similarly to how I describe the csv format above should not be supported by this library.

If its content can be wrapped by an abstraction of reading row by row, it can also be wrapped by an abstraction of reading sheet by sheet; Even if it means that there will always be only one sheet.

### Some readers define methods that make no sense on the interface.
Every reader implementation defines public methods that are not part of the `ReaderInterface` and make sense only within the context of the implementations that defines them.

As far as I can tell, all of these methods are setters that should be called only during setup.

Here is what I mean by that. Once a read object is built and its `open()` method is called it is ready for reading,  there is no longer a reason to call any of the following methods:

* **CSV**
  * `setFieldDelimiter`
  * `setFieldEnclosure`
* **XLSX**
  * `setTempFolder`
  * `setUseSharedStringsFileCache`

All of these methods are relevant only during the construction and configuration of the reader, after that they are just an implementation detail.

Since the code that is calling `ReaderFactory::create` has to know the file type it is reasonable to assume that the code will also know the exact implementation type that the factory will return. So it makes sense to leave these methods public for end user's factory wrapper to call before passing it to the processing code that type hints a `ReaderInterface`.

### Actual iterators instead of hasNext() and next()
This doesn't remove the question whether sheet functionality should be exposed by `ReaderInterface`, it simply changes from `hasNextSheet()` and `nextSheet()` to `getSheetIterator()`, and all of the same arguments still apply.

That being said, I think that a built-in iterator support is a great idea and I was going to suggest it after this issue was resolved. Since you brought it up, I'll create an issue for it now.

### Breaking up the inheritance

> * ReaderInterface
>   * CSV
>   * Spreadsheet
>     * XLSX

> How well would that fit into this plan?

It's an implementation detail that is not relevant to the consumers of the interface. At the end of the day, every implementation will perform a sequential read of a file containing multiple rows spread across zero to many sheets.

**Comment by adrilo** [comment]
Thanks for writing this detailed answer!

> The fact that it supports only one sheet is an implementation detail and should be no concern of the interface or its consumers.

I disagree. While this is theoritically true, from a consumer's perspective this feels wrong. If your goal is to read a CSV file, you probably won't think about doing `nextSheet()`.
A workaround for this issue would be to have a default implementation of `hasNextSheet()`, `nextSheet()` and make it optional to call these functions.

> Some file-formats don't have sheet support

You are right. *Multiple* sheets support is the key problem. All files have at least 1 sheet.
As long as we can come up with a solution that does not add too much complexity for the CSV-like readers, I'm fine merging the 2 interfaces.

> Actual iterators instead of hasNext() and next()

Agree that it won't solve the specific sheet problem. It's just nice :)

> Some readers define methods that make no sense on the interface.

You said that you only looked at the reader interface. But I'd like to solve this issue both for readers and writers as their interfaces are similar.
Both have specific functions to setup the created instance. As you mentioned, and I agree, those methods don't need to be part of the interface. The XLSX writer also defines functions to play with sheets. These functions can be part of an interface (since they will be shared by all writers that handle multiple sheets). They should not be part of the main WriterInterface though.

**Comment by Lewiscowles1986** [comment]
> The fact that it supports only one sheet is an implementation detail and should be no concern of the interface or its consumers.

I'd argue that in such a generic interface, the fact spreadsheets have multiple sheets, is more of an implementation detail, and therefore should not be the concern of the `ReaderInterface`, but another interface, class or trait (Thinking about this, a Trait may be the best fit for multiple sheet functionality).

**Comment by adrilo** [comment]
The trait is useful to share implementation but does not really help with the interface.

**Comment by Lewiscowles1986** [comment]
@adrilo what I am saying is this is *maybe*, not something for an interface, and something else needs to be done elsewhere, I am not 100% sure what, but I do think from the information given since the problem, another Interface may not be the ideal solution, and modifying ReaderInterface is definitely not ideal.

> As it stands the return type of ReaderFactory::create() method is XLSX while it can return both CSV and XLSX. Additionally XLSX defines methods (hasNextSheet() and nextSheet()) that are not present in neither CSV nor ReaderInterface

So to my understanding, this is an issue with accessing methods from something implemented in one, but not both concrete implementations of classes using ReaderInterface. There is nothing to say that a class cannot have public methods not defined within an interface, or abstract class, so while I agree that CSV and XLSX can be created. I do not think this in itself requires a change to the ReaderInterface, or is indicative of a problem.

**Comment by nCrazed** [comment]
> I disagree. While this is theoritically true, from a consumer's perspective this feels wrong. If your goal is to read a CSV file, you probably won't think about doing nextSheet().
**A workaround for this issue would be to have a default implementation of hasNextSheet(), nextSheet() and make it optional to call these functions.**

The highlighted part is essentially how I am suggesting to handle csv and any other single-sheet formats. 

> But I'd like to solve this issue both for readers and writers as their interfaces are similar.

Writer allows you to output your data either to a file or browser. The data can be outputted purely in sequence by writing row by row to the first sheet, then the next sheet and the next. Additionally, the order of the sheets can be non-sequential, you can even go back-and-forth between two or more sheets. The sheet interactions are complex enough to warrant separate interfaces for files that support them and ones that don't.

Reader simply opens an existing file on a file system for reading, advances through it one or many (in case of an early call to nextSheet()) rows at a time and closes the file handler. That's it.

While there are similarities between the readers and writers, they do two fundamentally different things in different ways.  I see no reason why simplicity of one should be sacrificed in order to maintain superficial similarity with the other

> There is nothing to say that a class cannot have public methods not defined within an interface, or abstract class, so while I agree that CSV and XLSX can be created. I do not think this in itself requires a change to the ReaderInterface, or is indicative of a problem.

If you are consuming a concrete class, you are free to use any of the public methods defined by it, they all belong to the interface of the class.

If you are consuming an interface that a class claims to implement (via the `implements` operator), you should only be invoking the methods that are defined by the interface. Attempting to use any other methods that happen to be implemented by the concrete class that you were given is an error-prone way to defeat the purpose of requesting an interface in the first place.

As it stands, only the CSV reader correctly implements the ReaderInterface, the XLSX reader claims to implement it, but if you attempt to use it via the defined interface, it breaks.

[Here](https://github.com/nCrazed/ReaderInterface-Problem) is an example consumer code with tests that demonstrate the problem.

There are two ways to address this:
* Split the interface into a RowReader and SheetReader (not necessary these names of course).

I am guessing that @Lewiscowles1986 suggestion to use traits is specifically for this approach.

There is a subtle problem with using inheritance to share the common parts of the interfaces (SheetReader extends RowReader). You end up with the same problem where an implementation of a SheetReader could be legally passed to a consumer of RowReader which would lead to an error.

This is due to the fact that any implementation of SheetReader will implement RowReader by an extension, but it will most likely not support the usage pattern defined by it. A workaround for this would be to implement the row handling methods in a way that support both patterns (similar to how the writer deals with the row-per-sheet limit).

* Add the sheet methods to the RederInterface

While I am suggesting that CSV could implement this new interface in a way that does not break its current usage pattern. It is not strictly necessary since the new interface can dictate a usage pattern requires a sheet to be selected before any rows can be read.

**Comment by Lewiscowles1986** [comment]
Just really quickly

> If you are consuming an interface that a class claims to implement (via the implements operator), you should only be invoking the methods that are defined by the interface. Attempting to use any other methods that happen to be implemented by the concrete class that you were given is an error-prone way to defeat the purpose of requesting an interface in the first place.

This is only true if you are accessing as an interface, without performing other checks. For example

```PHP
public function route(RequestInterface $request)
{
    
    switch($request->getSAPI())
    {
        case 'http':
            $this->response = $this->httpRoute($request);
            break;
        case 'cli':
            $this->response = $this->cliRoute($request);
            break;
    }
    return $this;
}
```

Within the `httpRoute` method called, we could of course type-hint in the definition to a class that implements `RequestInterface`, without mentioning `RequestInterface` as we know that the $request we receive has to be an implementer; so within that function we could access the type's extended properties and methods. Likewise for Inside the `cliRoute` method

> **N.b.** I know the code example has nothing to do with spouts problem domain, it is just an example, partially moved to another area because it might help highlight the point.

**Comment by adrilo** [comment]
Hey guys,

I had conversations with a bunch of people about this topic. While there are some pros and cons in all the solutions we mentioned, one turned out to be better than the others IMO:

I'll unify the interfaces of CSV and XLSX readers, introducing the concept of sheets in the CSV reader (pretty much what you proposed @nCrazed). While this may be confusing for the consumer of the library, it has a lot of benefits:
- same implementation for all reader types: if a program supports multiple types of files, there is no longer a need to check for the type to use the correct implementation
- easier to maintain/build upon: adding support for new types is more straight-forward as all readers will now be built the same way, with no exceptions
- I'm moving away from hasNext() / next(), to use PHP iterators instead. Having a common interface for the readers allowed me to have a clean interface (and again, sheet iterators are always exposed by the reader while row iterators are exposed by the sheets - CSV is not an exception)

Also, the confusing part of having a unique sheet in CSV can be overcomed by creating a wrapper around the readers, if needed.

Feel free to take a look at #73 that introduces the unified interfaces, along with the iterator support.

And thank you very much for this really interesting discussion :)
