### ISSUE TITLE
Performance counting rows

### ISSUE THREAD

**Issue by inspectorman** [box/spout#528]
Hello dear,

Firstly I would like to thank for your work.

I need your opinion about the performance on my application, I want to know if it's normal to take 131 seconds to read 130.000 rows. I'm just counting rows and showing it to user.

thanks in advance.

**Comment by adrilo** [comment]
Hi !

I'm assuming you're talking about an XLSX file here. According to the numbers [here](http://opensource.box.com/spout/faq/#how-long-does-it-take-to-generate-a-file-with-x-rows), if your file is using shared strings and has a few columns, then 131 seconds can make sense.

Shared strings is what makes it very slow, as Spout needs to build a cache on-disk. The part where you have to go through all the rows will be equally slow with shared and inline strings.

If you have control over the creation of the file, I'd suggest you to use inline strings instead of shared strings. That should really speed things up!
