### ISSUE TITLE
XLSX files not opening in Apple Numbers

### ISSUE THREAD

**Issue by kiessan** [box/spout#53]
When trying to open the XLSX file with Apple Numbers, the application alerts that the file cannot be opened. No further information is provided. However, changing the file extension to xls let Numers open that file.

**Comment by adrilo** [comment]
I was able to reproduce the bug on Numbers 3.5.3. It seems like Apple Numbers does not support inline strings (only support shared strings): https://github.com/jmcnamara/XlsxWriter/blob/master/dev/docs/source/bugs.rst#strings-arent-displayed-in-apple-numbers-in-constant_memory-mode

I tested with a file containing shared strings but it does not work either.

Since Spout omits a lot of XML tags, this issue requires more investigation to see which tag are actually needed to get the generated XLSX file working in Numbers

**Comment by adrilo** [comment]
@kiessan, #89 should have fixed the error message and you should now be able to open the file in Numbers!
Remember that you need to use shared strings with Numbers, as it does not seem to support inline strings (I'll take a closer look at this, see if I can do something about it). This means explicitely calling `$writer->setShouldUseInlineStrings(false);`

**Comment by adrilo** [comment]
It seems like there is nothing I can do to work around the Numbers issue with inline strings. So if you are targeting this software or any iOS platform (as the same problem occurs when trying to view an XLSX file in Safari on iPhone or iPad), please use shared strings instead of inline strings!
