### ISSUE TITLE
Setting border on cell or column

### ISSUE THREAD

**Issue by jankulma** [box/spout#548]
In #129 there is comment by @jordanade about setting fixed width to all columns in a sheet.

> Oh, figured it out--just added this line to Worksheet.php, startSheet(), between the header and the data:
> `fwrite($this->sheetFilePointer, '<cols><col min="1" max="1" width="100" customWidth="1"/><col min="2" max="6" width="30" customWidth="1"/></cols>');`

Would there be a similar way to set border for columns or particular cells? Where to look for the syntax and available attributes that can be used in there (I mean the `<cols><col ... ></col></cols>` syntax)?

**Comment by adrilo** [comment]
@jankulma you can find the entire specs here: https://www.ecma-international.org/publications/standards/Ecma-376.htm
It's pretty brutal to read (it contains the whole open xml specs, not only what's used in the spreadsheets).

However, if you look at this: http://opensource.box.com/spout/docs/#styling-rows, there's a section about borders. You can already set borders on rows, not sure if that's interesting to you.
Otherwise, the v3 release will add support for per cell styling, so you'll be able to control the borders on the cell directly (and therefore on the column).
