### ISSUE TITLE
Load specific row

### ISSUE THREAD

**Issue by AguinaldoAranda** [box/spout#549]
Hi everyone, everything ok?

I have a spreadsheet with 15,000 lines, it takes a while to read all the lines. But I need to get only the first line. Can I limit the loading to make the process faster?

I know that in the loop I can do this using "ifs", but if it is this way I will need to load every file and it takes, what I wanted to avoid is to load a file with 15 thousand lines to get only the data of the first one.

Has as?

NOTE: Sorry for English ....

**Comment by adrilo** [comment]
Well, unfortunately you can't really do otherwise than using the `if ($rowIndex === 1) { ... }`. It may take some time as Spout parses a bunch of files to prepare the data, whether it's the styles file (for things like dates - which I agree could be optional if date formatting is not turned on) or the strings file (where actual string data is stored).
Once this is done, Spout reads another file, row by row so if you stop after the first row, the 14,999 other rows won't be read. The problem is that the first row may be a date that we want to format, or may be a string whose reference needs to be looked up in the other "strings" file.

For these reasons, there's not much else we can do for now. There are definitely some optimizations but nothing planned yet.
