### ISSUE TITLE
Issue when building (intermittent)

### ISSUE THREAD

**Issue by Lewiscowles1986** [box/spout#57]
Box\Spout\Reader\XLSXTest::testReadShouldBeProtectedAgainstBillionLaughsAttack

Even if I build master, this seems to fail to assert for PHP5.6 only... How did TravisCI pass the build, if this always fails?

**Comment by adrilo** [comment]
What's the error? I guess it's related to memory consumption. The limit in
the test is pretty low so I guess the memory usage in TravisCI is just
below the threshold while yours is just above.

**Comment by Lewiscowles1986** [comment]
Exactly, and I just watched your build fail too, which made me feel better. I also have a test by branching master with no mods and adding an edit to the readme.me (therefore outside the build tests I hope)

**Comment by adrilo** [comment]
This specific test is to make sure Spout is not subject to the [Billion Laugh Attack](https://en.wikipedia.org/wiki/Billion_laughs). If the security hole is present, it would crash the program by consuming all the available memory.

**Comment by Lewiscowles1986** [comment]
With the greatest of respect, it looks like that could be dealt with, by disabling parsing nested entities within entities, at a depth of $n, where you can set $n to be any valid integer... In fact that would actually potentially remit the billion laugh attack, whereas this seems to report on it, at least with the setup PHP5.6 has on Travis.

**Comment by adrilo** [comment]
I totally agree and this is already done in Spout (at least I thought). For example: https://github.com/box/spout/blob/d4cf85327026d62d5975dff086e19518722b598b/src/Spout/Reader/Helper/XLSX/SharedStringsHelper.php#L115

I re-ran some tests to make sure the code was safe but it seems like it's not perfect. While the default libxml settings will prevent the billion laughs attack, it won't prevent the Quadratic Entity blowup. So I'm going to fix that.

BTW what I meant was "Spout is already protected, otherwise it would take 3GB of memory not 25MB". So bumping the limit was just to make sure it would pass on all systems.

**Comment by Lewiscowles1986** [comment]
;) Legend, glad you are involved, these things happen. 

libxml_disable_entity_loader(true);
from https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing, which also links to https://www.sensepost.com/blog/2014/revisting-xxe-and-abusing-protocols/

Happy to help if you are busy

**Comment by adrilo** [comment]
I had this line before. Unfortunately, there is a bug with it... https://bugs.php.net/bug.php?id=62577
libxml_disable_entity_loader() also disables XmlReader::open() which is used by the XLSX reader to read XML.

So adding this is not possible... I can add another option though to protect from the quadratic entity issue.
