### ISSUE TITLE
Streaming XLSX download with 100k records for browser requires downloader a long wait before download begins.

### ISSUE THREAD

**Issue by bs-thomas** [box/spout#582]
I would like to stream the XLSX for the browser to download a very large table (well not so large, but big enough).  (Around 100k records).

I have the following code:

```
$writer = \Box\Spout\Writer\WriterFactory::create(\Box\Spout\Common\Type::XLSX); // for XLSX files
$writer->openToBrowser('cool.xlsx'); // stream data directly to the browser

$pdo = \DB::getPdo();
$query=$pdo->prepare('SELECT * FROM auction_lot');
$query->execute();

while( $row = $query->fetch(\PDO::FETCH_ASSOC) ) {
    $writer->addRow($row);
}

$writer->close();
exit();
```

I noticed that after the user clicks on download, the user will have to wait completely for the preparation of the data until Chrome pops up the XLSX download (assuming that is when exit() is called).

Is it possible to immediately start allowing the user to download the contents when the server is running the while loop?

On a side note, (kinda off topic, but related) I've used another library called ZipStream (https://github.com/maennchen/ZipStream-PHP), and it allows me to combine a bunch of files together and allow the visitor to download these files as a ZIP file.  Let's say I'm combining 100 files, once the first file got prepared, immediately this library outputs this info to the user and the user starts downloading without any types of long wait.  Downside is the user doesn't know how big the download is, but advantage is he gets an immediate response when clicking download.

I wonder if this is possible also with this package?

Your help is appreciated.

**Comment by bs-thomas** [comment]
Oooo, and I noticed that this issue does not happen for CSV files.  When I export CSVs, it's almost instant, lightning speed!!

**Comment by adrilo** [comment]
@bs-thomas What you experienced is the normal behavior:
- CSV files can be streamed because their structure is simple: each new row is a new line in the file, there's only one file involved.
- XLSX (and ODS) files on the other hand can't be streamed: these are a bunch of XML files, zipped together. The problem is that some files' content depends on other files' content: one file will contain the added rows, another file will contain references to the cell values or styles, another one will contain the number of rows/sheets, etc. This means that you can't close any XML file until the end and therefore can't send anything to the client as content may be updated.

Using the library you mentioned cannot help unfortunately (it's an interesting library though!).

**Comment by wikt0r** [comment]
Unfortunately I am not very experienced in XLSX internal format, but I found two different projects where they promise streaming feature into XLSX files.

https://github.com/apify/xlsx-stream
https://github.com/Polyconseil/xlsx_streaming

I suppose there are a lot of restrictions in this case, but maybe it can work in special cases.

**Comment by adrilo** [comment]
Spout also "streams" data internally. What this means is that it does not retain the whole spreadsheet data in memory but only the line being written. Once written, it forgets about it. This technique allows the library to write extremely large spreadsheets without running out of memory.
This is what other libraries are promising as well. It has nothing to do with the browser download, which is as far as I know, not possible due to the constraints mentioned above.
