### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by Romain-Moreaux** [box/spout#588]
if you are working with large files, you may exceed the execution limit of the script especially if you use loops and you should see this error php `Fatal error: Maximum execution time of 30 seconds exceeded in ...`

You could extend the maximum execution time using `ini_set('max_execution_time', 300);` at the top of your file.

This is extend to 5 minutes.

**Comment by adrilo** [comment]
@Romain-Moreaux are you suggesting we add that somewhere in Spout? I'm not really clear what the goal of this issue is.

**Comment by Romain-Moreaux** [comment]
C'etait juste une aide pour les gens qui auront le meme probleme.

Je ne sais pas si tu peux faire quelque chose pour cela étant donné que c'est une option de configuration php ?

**Comment by adrilo** [comment]
[Back to English for non-French speakers]
IMO it's not Spout's role to set the max execution time of your PHP script. This setting affect the whole execution of the script (not just Spout's execution) and should be handled by developers directly since they are the only one who know what value to set.
I did not include this in the doc as this is a rather well known setting and a Google search with the error message gives you this answer in less than 10sec.

Thanks for sharing though, it's another way people may find the solution of this error.
