### ISSUE TITLE
For when to read in batches??

### ISSUE THREAD

**Issue by davidNieves** [box/spout#598]
Hi team!

Im working with huge files, will be great if we can set a "range" to read xlsx/csv/ods rows and split our processes in batches, I think that in current version is not possible do it? Do you intend to add this improvement in the future? I can pay for it...

Thanks!!

**Comment by adrilo** [comment]
Hi @davidNieves !

Setting a range is interesting but the perf gains won't be significant. This is because we can't really jump to a given row by skipping lines in the XML files. In other words, if you want to start reading from row 10, you still have to go through the first 9 rows to position your file pointer at the right place.

You could potentially use some dichotomy process to move the pointer faster, but with XML you need to be positioned exactly at the beginning of the `<` to be able to read the node and get its type (to know if it's a "row" node and which row it is). So overall, I think it would be slower than reading the whole file.

Using inline strings in your original spreadsheet does speed up the processing a lot though, if you can control how it's generated.

BTW something was done already: https://github.com/box/spout/pull/568

**Comment by davidNieves** [comment]
Hi @adrilo ! thanks you so much by the information! I have 2 questions:

Why are you talking about XML?? Im working with format XLSX,ODS AND CSV... maybe you mean XLSX instead of XML??
2.- Then, like I readed in #568 I can do it, but I have to read again all file in each loop, correct?? example:
I WANT THAT PROCESS GO 50 IN EACH LOOP, AND THE FILE HAS 120 ROWS:

$reader->open($csv);
$reader->setStartColumnIndex(0);
$reader->setEndColumnIndex(49);

NEW LOOP:

$reader->open($csv);
$reader->setStartColumnIndex(50);
$reader->setEndColumnIndex(99);

NEW LOOP:

$reader->open($csv);
$reader->setStartColumnIndex(100);
$reader->setEndColumnIndex(120);

**Comment by adrilo** [comment]
My bad, I should have added that XLSX and ODS are 2 file formats based on XML. A XLSX or ODS file is basically a bunch of XML files describing the spreadsheet, zipped together. Spout abstracts away the processing of these XML files.

CSV files are different as they are regular files. In your case, can you explain what you're trying to do exactly? If you're trying to read batches of 20 rows for instance, you can already do that. You don't have to read the entire file at once.

**Comment by davidNieves** [comment]
Hi @adrilo ! thanks you so much by your response!

In my case, client are importing XLSX file that contain 50.000 products, the process is "overpassing" his server limits and server crash, then I was thinking about possibility of do this process by batches. Like Im calling via ajax to start import process, I can do multiple ajax calls to process file from range elements in excel.... I hope was clear, else, I can do more details!

Thanks you so much!

**Comment by adrilo** [comment]
Hmmm processing in batch may help. You can already try it though:
```
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $rowIndex => $row) {
        if ($rowIndex >= $startingRow && $rowIndex < $endingRow) {
           // only get data for your batch
        }
    }
}
```
`$startingRow` and `$endingRow` are params sent by your client.

The problem is that with big files, a lot of time is spent reading the cells values and we have to read ALL the values even though we only process part of the file. Hence my assumption that it may not work.

**Comment by davidNieves** [comment]
@adrilo Exactly! this is the main problem.... I thought in do next:

1. Read all data.
2. Save all array with json_encode in a temp .json file.
3. Use "file_get_contents" + json decode in each loop to get indexes....

Maybe by this way will be faster?? what do you think about it?

THANKS YOU SO MUCH!

**Comment by adrilo** [comment]
If you can pre-process the XLSX file, then you should convert the XLSX file to CSV and eventually split it into smaller chunks. With CSV you can stream data to the client so as soon as you start reading the file, you can send data back to the browser and start displaying it.

**Comment by davidNieves** [comment]
Hi @adrilo ! thanks you so much! then you suggest transform XLSX to CSV because in CSV file is allowed read rows by range??

**Comment by adrilo** [comment]
CSV because it's faster to process and can easily be split into multiple files, each containing N rows.
Even the PR I showed you about range support won't help for performance (its purpose is different).

**Comment by davidNieves** [comment]
All clear now @adrilo only final question, maybe you have a complete example that shows how to split into multiple files?? THANKS YOU SO MUCH BY YOUR TIME!

**Comment by adrilo** [comment]
I don't have such an example. You can use a Linux tool to do this: `split -l 50 bigfile.csv smallfile-`

**Comment by adrilo** [comment]
There are some functions to execute commands directly: `exec`, `system`, `passthru`. For instance: `exec('split -l 50 bigfile.csv smallfile-');`. It's not usually recommended to let PHP run these types of command as it opens a security vulnerability. But then, it's up to you and your environment.

Otherwise you can read the XLSX, write a CSV file with the contents read, creating a new CSV file every 10,000 rows for instance. Then your client can make multiple calls to get the data of each file.
This obviously only works if you can pre-process the file. If you expect your user to upload a XLSX file and have something displayed on the page immediately, you're out of luck. You'll have to make your user wait

**Comment by davidNieves** [comment]
@adrilo  Perfect! Understand, thanks you so much! =) I hope that our conversation help in future to users with this same question!

Have a nice week!
