### ISSUE TITLE
Fatal error: Uncaught exception 'Box\Spout\Common\Exception\InvalidArgumentException' with message 'Trying to add a value that exceeds the maximum number

### ISSUE THREAD

**Issue by ryzulla** [box/spout#627]
Hi all, i just trying to export data with spout but when i exported file corrupt, and when i trace whats the error he saya Fatal error: Uncaught exception 'Box\Spout\Common\Exception\InvalidArgumentException' with message 'Trying to add a value that exceeds the maximum number

whats the problem?

**Comment by madflow** [comment]
The error message is pretty self descriptive I would assume:

```PHP
if ($this->stringHelper->getStringLength($cellValue) > self::MAX_CHARACTERS_PER_CELL) {
  throw new InvalidArgumentException('Trying to add a value that exceeds the maximum number of characters allowed in a cell (32,767)');
}
```

Here is some documentation about Excel Limits:

    /**
     * Maximum number of characters a cell can contain
     * @see https://support.office.com/en-us/article/Excel-specifications-and-limits-16c69c74-3d6a-4aaf-ba35-e6eb276e8eaa [Excel 2007]
     * @see https://support.office.com/en-us/article/Excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3 [Excel 2010]
     * @see https://support.office.com/en-us/article/Excel-specifications-and-limits-ca36e2dc-1f09-4620-b726-67c00b05040f [Excel 2013/2016]
     */

**Comment by fasttrackhost** [comment]
Why not simply cut the string thats longer the 32767 chars limit?
It seems that the xls will not be writen to disc if this limit ocurs.

Could this simply turn into a notice? make the string shorter than the limit and let script go on.

The problem is that this simple line:

WriterEntityFactory::createRowFromArray($simpleArray);

**will fail**, and we had to go the long way arround in order to make it work.

This would be a great improvement. Thank you.
