### ISSUE TITLE
problem when exporting number, can't sum data in Excel

### ISSUE THREAD

**Issue by maulayyacyber** [box/spout#635]
I have a problem when exporting number, there I can't sum data in Excel, any idea ?

![Screen Shot 2019-04-08 at 08 57 56](https://user-images.githubusercontent.com/11194525/55694074-89bc3180-59dc-11e9-96ce-29d4ec637016.png)

**Comment by adrilo** [comment]
@maulayyacyber Are you trying to sum numbers from the Payment column? Could you share the XLSX file that you generated?

**Comment by spras** [comment]
Hi, same problem here.
I think it's because spout can't set the cell type.

When trying to sum the cells in column C, when get 0 because they are stored as string : 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/531749/58456788-646aba80-8125-11e9-8932-64a0a96ca9d3.png">

we have to convert it to number in order to manage to sum it :
<img width="574" alt="image" src="https://user-images.githubusercontent.com/531749/58456821-764c5d80-8125-11e9-82e6-ee18fb424be7.png">

here the xls file
[EXPORT TOUTES OPERATIONS_20190527122408.xlsx](https://github.com/box/spout/files/3225987/EXPORT.TOUTES.OPERATIONS_20190527122408.xlsx)

The "convert" manual operation is problematic for us.
Is there a solution ? Thank's

**Comment by markosko** [comment]
@spras Take care of not having number written as string in php, `$var = 5.2 !== $var="5.2"`
without code or source of numbers hard to say
