### ISSUE TITLE
Using iterator_to_array causes infinite loop

### ISSUE THREAD

**Issue by Llbe** [box/spout#657]
Running the code below with the `iterator_to_array` call causes an infinite loop, while removing the call executes normally. I've tried with multiple ODS files and I believe this is reproducible with any simple file, e.g. a single cell with "foo" in it (`A1`).

Note that the inner foreach is required (the infinite loop is with the inner foreach I presume).

PHP 7.3 and Spout 3.0.0.

    use Box\Spout\Reader\Common\Creator\ReaderEntityFactory;

    $path = '/tmp/filey24aZ9.ods';

    $reader = ReaderEntityFactory::createReaderFromFile($path);

    $reader->open($path);

    foreach (iterator_to_array ($reader->getSheetIterator()) as $sheet)
      {
        foreach ($sheet->getRowIterator() as $row) { }
      }

**Comment by adrilo** [comment]
Hi @Llbe,

Indeed using `iterator_to_array` does not work for ODS files. This is a limitation that does not have a workaround, so I can only suggest not using it.

`iterator_to_array` forces to iterate over ALL the values of the iterator. In the case of an ODS file, this causes the parsing of an XML file that also contains the row data. Because the sheets and the row data are packaged in the same file, reading all sheets means reading the entire XML file. That means when you try to read row data, the file pointer is already at the end of the file so there's no more data to read.

I agree that there's a bug causing the infinite loop, however I'd argue that fixing the bug will not help that much as using `iterator_to_array` would prevent any rows to be read.
