### ISSUE TITLE
XLSX on windows

### ISSUE THREAD

**Issue by aduhaime-arm** [box/spout#680]
Hi, I am encountering problem while opening .xslx files generated by Spout on Windows devices. I am getting the following message:
`Excel cannot open the file report.xlsx because the file format or extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file` 
It works fines with Ubuntu using LibreOffice and also using a free online xlsx viewer (sheet.zoho.com)
## Debug info
This is the result of the command `php -i | grep Libzip`
```
Libzip headers version => 1.3.2
Libzip library version => 1.5.1
```
Unzipping it did work without any error
Tried opening on Windows 10 using Excel
I am joining a copy of the file
Version of Spout: `3.0.1`
[report (84).xlsx](https://github.com/box/spout/files/3618242/report.84.xlsx)

**Comment by Airmole** [comment]
Ahhh，Me too.
啊，我也一样

**Comment by adrilo** [comment]
Hi @aduhaime-arm,

The file you attached is an ODS file (created using `Type::ODS`). You used the `xlsx` extension, but this is incorrect. I'm guessing that's why Excel is having trouble opening the file. LibreOffice and zoho probably don't rely on the file extension to detect the actual file type, that's why it works.
