### ISSUE TITLE
Is there a way to find cell by text in it?

### ISSUE THREAD

**Issue by DenisAlliswell** [box/spout#69]
I'm wondering is it possible in this lib to find certain cell by some content(text) in it?

I need to find cell this way and add new cell just right after it.

**Comment by adrilo** [comment]
Hi @DenisAlliswell, can you please give more details about what you are trying to accomplish?
Are you trying to create a new XLSX file from another one (with more cells)? Or do you only need to have the new data stored in memory?

**Comment by DenisAlliswell** [comment]
Hi @adrilo! I need to open existed file, find the certain cell by text in it and create new cell just after it. In other words, I need to find cell and know it exact coordinates.

**Comment by adrilo** [comment]
The way Spout works is different from other libraries. To avoid the common Out of Memory issues, the document is not stored in memory. The only way to access the data is reading it line by line. Same goes for writing: you can't say "Write this value in cell B12". If you need to write something in B12, you need to write data in the previous 11 rows because you can't go back.

Even though there are some limitations, you should still be able to solve your problem this way:

```
$reader = ReaderFactory::create(Type::XLSX);
$reader->open('path/to/existing/file.xlsx');

$writer = WriterFactory::create(Type::XLSX);
$writer->openToFile('path/to/file/to/create.xlsx');

while ($reader->hasNextSheet()) {
    $reader->nextSheet();

    while ($reader->hasNextRow()) {
        $row = $reader->nextRow();

        $columnIndex = array_search("TEXT_YOU_SEARCH", $row); // replace with the actual text
        if ($columnIndex !== false) {
            array_splice($row, columnIndex, 0, "TEXT_TO_ADD");
            $writer->addRow($row);
        }
    }
}

$reader->close();
$writer->close();
```

This should do pretty much what you are trying to do: it reads the existing file, row by row. For each row, it searches if one of the cell contains some text. If so, it gets the column index and adds some other text in the next cell, shifting existing data to the right. It then saves the updated row to a new XLSX file.
In the end, the created XLSX file should contain the correct data.

Let me know if you need more help!

**Comment by DenisAlliswell** [comment]
Thank you @adrilo! Gonna test it! Hope it helps! :+1:

**Comment by adrilo** [comment]
Closing this issue as it seems that the proposed solution worked
