### ISSUE TITLE
Missing files during installation

### ISSUE THREAD

**Issue by juanmiguel431** [box/spout#708]
When I install the version 3.0.1 through composer (composer require box/spout 3.0.1) does not install the class CellAlignment.php. 
Even, the editor cannot find the method setCellAlignment, it does not exists. Why this happen?

**Comment by adrilo** [comment]
Here is what changed since the latest release v3.0.1: https://github.com/box/spout/compare/v3.0.1...7964dad
As you can see, CellAlignment is part of these commits. This means that unless you fetch the master branch, you won't be able to get CellAlignment as of now.

I'm gonna cut a new release as there is a reasonable amount of changes that can be made available. You'll then be able to fetch the version 3.1.0.
