### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by tyteen4a03** [box/spout#754]
Looking for a PHPSpreadsheet alternative and this came up, but there hasn't been any activity for the past few months.

**Comment by neverender24** [comment]
I just used this and it worked great, faster than PHPSpreadsheet.

**Comment by adrilo** [comment]
Hi @tyteen4a03 ! Unfortunately I did not really have time to take care of this project for a while.
I'm still looking at issues and can provide help if needed but I won't work on new features :(

**Comment by seboettg** [comment]
@adrilo Do you need support for maintaining this library. I mean, it would be very sad if this wonderful library is no longer maintained. Spout seems to be well structured and the code is not so complicated to understand, so I think I could be a helpful support... What do you think?

**Comment by adrilo** [comment]
Thanks for your support @seboettg ! I no longer work at Box and was removed from the Github org so I lost my "admin" privileges. This makes it harder to provide good support for Spout.
Regarding external help, I would love to see that. However, I would need to check with Box first as I'm not sure what their policy is...

**Comment by 1stthomas** [comment]
The repository is under Apache 2.0 license. A fork would not be easy to maintain under this circumstance. I would love, if Box changes the license to the MIT license..

**Comment by TonisOrmisson** [comment]
It would help to get some statement from Box on what is the future of this package on their behalf. Maybe @adrilo can refer someone from Box team to whom the users of this package could turn to clarify the status of this project? It's a sad to see community contributing and using this package but no-one to administer the project. 

I suggest finding a suitable Box contact and asking them whats their plan?

**Comment by adrilo** [comment]
Hello all! Sorry for the long silence.

A few months ago, I was removed from the Box org (I'm no longer working there) and lost my admin permissions on this project. This prevented me from maintaining it properly (I could not merge PRs, close issues...). As a consequence, on top of the little time I have to invest in that project, I stopped looking at PRs and issues.

Although, 2 weeks ago I got in touch with someone from Box. They gave me back the admin permissions on the repo, so that I can now be more productive. It's still going to be hard for me to find time to work on Spout, but at least I can reply to issues and stuff.

If you feel like this maintenance mode does not fit your needs, feel free to fork the project :) That's what open source is about after all!
