### ISSUE TITLE
Xlsx cell getBackgroundColor and getFontColor not working

### ISSUE THREAD

**Issue by uginroot** [box/spout#758]
### Code:
```php
$pathToXlsx = __DIR__ . '/test.xlsx';
$reader = ReaderEntityFactory::createXLSXReader();
$reader->open($pathToXlsx);

/** @var Sheet $sheet */
foreach ($reader->getSheetIterator() as $sheet){
    echo sprintf('Sheet: %s', $sheet->getName()) . PHP_EOL;

    /** @var Row $row */
    foreach ($sheet->getRowIterator() as $index => $row){
        echo sprintf('Row: %d', $index) . PHP_EOL;
        foreach ($row->getCells() as $indexCell => $cell){
            echo
                sprintf(
                    'Cell index: %d, value: %s, background color: %s, font color: %s',
                    $indexCell,
                    $cell->getValue(),
                    $cell->getStyle()->getBackgroundColor(),
                    $cell->getStyle()->getFontColor()
                ) .
                PHP_EOL
            ;
        }
    }
}
```

### Result:
```
Sheet: Sheet1
Row: 1
Cell: 0, value: 1, background color: , font color: 000000
Cell: 1, value: 2, background color: , font color: 000000
Cell: 2, value: 3, background color: , font color: 000000
Cell: 3, value: 4, background color: , font color: 000000
Cell: 4, value: 6, background color: , font color: 000000
Cell: 5, value: 7, background color: , font color: 000000
Cell: 6, value: 8, background color: , font color: 000000
```

### Expected:
```
Sheet: Sheet1
Row: 1
Cell index: 0, value: 1, background color: F2F2F2, font color: 385623
Cell index: 1, value: 2, background color: 7F7F7F, font color: 223962
Cell index: 2, value: 3, background color: CFCFCF, font color: 7F6000
Cell index: 3, value: 4, background color: D9DCE1, font color: 525252
Cell index: 4, value: 6, background color: DEEAF6, font color: 763E18
Cell index: 5, value: 7, background color: FBE4D5, font color: 2D4D6A
Cell index: 6, value: 8, background color: ECECEC, font color: 222A35
```

**Comment by madflow** [comment]
The reader does not support styles. This is tracked here: https://github.com/box/spout/issues/513

So currently - the first result is considered to be the expected result.

**Comment by Pistle** [comment]
Color is not data.

The Get.cell technique has flaws.

It does not update as soon as the cell color changes, but only when the cell (or the sheet) is recalculated.
It does not have sufficient numbers for the millions of colors that are available in modern Excel. See the screenshot and notice how the different intensities of yellow or purple all have the same number.
enter image description here

That does not surprise, since the Get.cell uses an old XML command, i.e. a command from the macro language Excel used before VBA was introduced. At that time, Excel colors were limited to less than 60.

Again: Color is not data.

If you want to color-code your cells, use conditional formatting based on the cell values or based on rules that can be expressed with logical formulas. The logic that leads to conditional formatting can also be used in other places to report on the data, regardless of the color value of the cell.

**Comment by uginroot** [comment]
It was not my decision to use color coding for cells with different data types. I needed to write a parser for tables and then transfer them to mysql. As a result, I had to use a heavier library for these purposes.
