### ISSUE TITLE
Get no of longest row in sheet

### ISSUE THREAD

**Issue by LocalHeroPro** [box/spout#794]
How to get number of the longest row in the sheet.
Sometimes one row have 10 and other row have 100 columns.
So how to determine last - first - empty column?

**Comment by adrilo** [comment]
Hi! There's no reliable way to do that in an efficient manner. The only way is to parse the entire file. This is because the section that describes the structure of the file (max row, max column) is optional. Some softwares add it, some don't. And if they don't, you have no other way than checking the number of columns row by row.

**Comment by LocalHeroPro** [comment]
So can that plugin have that feature built in?

**Comment by adrilo** [comment]
There's no plan to do it, as it can easily be done with the existing methods.
Having that done internally would not give better results and would add extra complexity that we're not ready/willing to handle at the moment. Hope you understand.

**Comment by LocalHeroPro** [comment]
>  as it can easily be done with the existing methods.
Could you show for me that method? Some link to example?

**Comment by adrilo** [comment]
Something like this:
```
$maxRowSize = 0;
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {
        $maxRowSize = max($maxRowSize, count($row->getCells());
    }
}
```
