### ISSUE TITLE
Thanks to package authors! How does it work?

### ISSUE THREAD

**Issue by acirulis** [box/spout#849]
First, huge thanks to the package authors! I was struggling with importing large Excel file (~20Mb, ~200k rows) with popular library PhpSpreadsheet - it just kept crashing after consuming few Gb of RAM. While they have some sort of "read filters", it didn't help - from what I understand, whole file is still parsed before applying any filters.
I also tried Linux binary ssconvert which seems to do the job but require additional installs. Then I accidently stumbled on box/spout via random SO article - SEO definitely needs improving, as this is high quality package from great team (checked out other box opensource projects) :)
I also wanted to ask (just for sake of education), how does this package works and differs from PhpSpreadsheet? I am not very familiar with XLSX specs but by checking .xlsx archive, I can see multiple large files, such as calcChain.xml, sharedStrings.xml and worksheet itself. How can they all be read as a streaming resource?
Why doesn't PhpSpreadsheet implement same approach? What are the drawbacks?

Thanks again!

**Comment by adrilo** [comment]
Hi @acirulis! Thanks for the kind words, always appreciated :)

An XLSX/ODS file is indeed an archive with many files describing the contents/style of the spreadsheet.
PhpSpreadsheet (and most others) way of doing things is to load all these files in memory to keep a full picture of all elements, at all times: data, cell/row styles, spreadsheet config, ... For large spreadsheet, the amount of data is too big to fit in memory, hence the crash! On the other hand, it gives you a lot of freedom: you can access/edit any cell, can you change styles at any time, etc...

Spout's approach is different. For reading, it reads the structure row by row (keeping a single row in memory at a time) and read the cells content as well as cells styles (located in other files), mapping content/style to cell, for the given read row. There are some optimizations because it's possible that not all cell contents fit into memory. This definitely limits the amount of data that needs to be stored in memory. The drawback is that you can only access 1 row at a time. If you want to read the 90th row, you need to read the 89th first rows. To know how many rows are in the spreadsheet (useful for progress), then you must read the entire spreadsheet...
Same goes for writing. You need to write row by row. You can't go back; once row2 is written, you cannot make changes to it later. This way, you have only a single row in memory at a time.

That's more or less how Spout can handle large spreadsheets, and why other libraries can't handle them!
Hope that's clear :)
