### ISSUE TITLE
Recommend to use shared-strings when writing

### ISSUE THREAD

**Issue by chrisgraham** [box/spout#9]
At least some versions of Excel (testing on Excel Mac 2011) have a bug with inline-strings. If an inline-string has a line break in it, it won't render. I have tried playing with line-ending formats, and it's not related to that. I have checked in a hex editor to confirm the output. If you then subsequently edit the sheet in Excel, Excel shifts things into its shared-string preference, and suddenly it all starts working.

I'm pretty sure this is a flat-out Microsoft bug, with them not using inline-strings natively, and hence not testing them well. It does not affect LibreOffice.

I recommend documenting this, as it impacts users here.

**Comment by adrilo** [comment]
Thanks @chrisgraham!

I think the problem here is different. It's more a styling issue than a string issue. If you have a line break in a string (for instance "the\nstring", it will be displayed as "the string" in Mac Excel 2011. Windows version (at least 2010) will display it "thestring" (no space).
However, if you look at what's actually in the cell, you can see that the string is on 2 lines. What's missing is a style telling Excel to wrap text. (This is what Excel - and the "AdvancedValueBinder" of PHPExcel - adds automatically when it detects new line characters).

The improvement here would be to add this "wrap text" style to the cells that contain multi-lines string. It requires first to support styling (which you added in #5 - still need to review it).

**Comment by chrisgraham** [comment]
Hi,

Well, when you double click to try and alter it, the actual input string is running on as if they were spaces.

I am going a bit loco with my fork. You can merge whatever you want from it, but I'm making opinionated decisions you may or may not agree with. For example, hard-coding the first row as bold, with whatever the format can do for that. I think that's good, as we're outputting basically table dumps, with a header row -- but you might consider making it a setting for example.
Some of my newer commits (not in the pull request) fix some bugs in my earlier code.

Probably you'll want to assess it all into one diff, apply that, then make changes, then commit it in one go.

**Comment by adrilo** [comment]
Closing this issue in favor of #10
