### ISSUE TITLE
Generated XLSX shows error when opened in MS Excel

### ISSUE THREAD

**Issue by webhdx** [box/spout#90]
There seems to be an error in workbook.xml, as I always get a message dialog when opening generated files in MS Excel. Files can be opened but they need to be repaired. Are you aware of the issue?

**Comment by adrilo** [comment]
Hi!
Thanks for reporting this issue. I'm not aware of that. It's likely to be
specific to an Excel version as the tests I ran worked fine.
Can you please tell me which version you are using? Windows or Mac? Also
are you using the latest version of Spout (2.x)?

Last thing: if you could copy here the error message after Excel has
repaired the file, it would be super helpful!

Thanks !

**Comment by webhdx** [comment]
I'm using the newest Spout (cloned repo today) and Excel 2013 on my Windows machine. This dialog appears every time you open a file generated by Spout:
![excel spout issue](https://cloud.githubusercontent.com/assets/10212760/9406231/db4f5426-47fe-11e5-954b-4ce9d02d8fb8.png)

Sorry for Polish language. It says that the file needed to be repaired in order to be viewed. It points to the problem with some properties in /xl/workbook.xml. 

My client also reported the problem but I'm not sure what Excel version does he use. Files can be opened in LibreOffice Calc (tested it on Ubuntu) without any issues.

BTW. I can provide you an example file if you need one.

**Comment by webhdx** [comment]
Further investigation showed that the problem was caused by Sheet::setName() method. Commented that out and the error no longer appears. Also even though LibreOffice Calc opened files without any issues, worksheet name wasn't set at all. I might create another issue for that if you want.

**Comment by adrilo** [comment]
Thanks for investigating @webhdx ! The issue comes from the "/" character in the name.
There are actually a bunch of restrictions on the name:
- the name should not exceed 31 characters
- the name should not contain these characters: \ / ? * [ or ]
- the name should not be blank
- the name should be unique

I'll add a check to make sure the sheet's name is valid and throw an exception on invalid names. Handling invalid characters will be the developer's responsibility. Spout should not try to change the name of the sheet, as developers may rely on this name to be whatever they passed in.

I suggest you to sanitize the sheet name the way you want before setting it. Something like: `str_replace(['\\', '/', '?', '*', '[', ']'], '_', $sheetName)` should work. Also make sure that the other requirements are met (you can truncate and verify the string is not empty) if you are dynamically setting the sheet's name

**Comment by devnix** [comment]
@adrilo Are these restrictions documented somewhere? I think I've been generating sheets with more than 31 characters with PhpSpreadsheet for ages...

**Comment by adrilo** [comment]
I believe it comes from the OOXML spec. I commented such a long time ago, but I can't imagine that I made these rules up :)
Note that the spec is one thing, the actual implementation may or may not respect the spec. That may be why it works with more than 31 characters (or maybe PHPSpreadsheet truncates the sheet name? Or Excel does?)

**Comment by devnix** [comment]
No, Excel does open the file, and if you want to rename a sheet with more than 31 characters, you will have to truncate it manually 😄
